### PR TITLE
Fiber runtime 2.0

### PR DESCRIPTION
**Pull request by vasilmkd**
Don't mind me, I'm just dumping some code I've been working on for the last 3 months.

In all seriousness, thank you for being a great community and for letting me do crazy experiments like this. I really feel welcome in this project, it has absolutely changed my life for the better, and it's a pleasure to be able to say that I have worked with some of you here and call you all my peers.

The code is functional (functional as in working, otherwise it looks like C with Scala syntax) enough, feel free to comb through it, but beware, there are no comments. I'll make sure to change that over the coming period. Feel free to experiment with it if you want.

I'm marking it as a draft because there are still changes that will be coming, and I'm also known for squashing commits and force pushing all the time, so maybe it's not the best idea to rebase on this branch for now.

I'm negotiating to get a powerful VM from my previous university to benchmark this on in the coming days, so stay tuned for that.

For now, there are indications that we can expect >5% improvement vs the current runtime under full load (due to reduced thread contention), better single thread fiber performance (I'm yet to test this properly, but I've seen significantly better scores on some single threaded benchmarks).

There's initial support for `scala.concurrent.blocking`. I'll make some improvements as I clean up the code, but it's already working. It would be really helpful if we can test situations where the current runtime deadlocks.

Finally, I'd like to extend a special thank you to @djspiewak for surviving the constant bombardment of questions, random links and reading through 3 A.M. ideas, and for helping me with the testing.

Thank you all again, for everything.

### CODE REVIEW

**Comment by SystemFw** [comment]
Does this subsume https://github.com/typelevel/cats-effect/pull/1586/files (sorry, haven't had the time to go through that one yet)

**Comment by vasilmkd** [comment]
@SystemFw you beat me to it, I just closed it. Yes it does.

**Comment by vasilmkd** [comment]
I have also tested the runtime with `fs2` and all tests are passing properly.

**Comment by vasilmkd** [comment]
| Benchmark                  |        series/3.x |       | error      | unit      |       new runtime |       |error       | unit      |
|:-------------------------- | -----------------:|:-----:|:---------- |:-----     | -----------------:|:-----:|:---------- |:--------- |
| DeepBindBenchmark.async    |           657.192 |   ±   | 5.175      | ops/s     |       **822.933** | **±** | **14.731** | **ops/s** |
| DeepBindBenchmark.delay    |          1621.563 |   ±   | 41.299     | ops/s     |      **2021.980** | **±** | **24.004** | **ops/s** |
| DeepBindBenchmark.pure     |      **2021.980** | **±** | **24.004** | **ops/s** |          1973.118 |   ±   | 41.136     | ops/s     |
| ShallowBindBenchmark.async |           640.043 |   ±   | 6.998      | ops/s     |       **813.917** | **±** | **9.023**  | **ops/s** |
| ShallowBindBenchmark.delay |          1643.392 |   ±   | 47.521     | ops/s     |      **1652.602** | **±** | **27.000** | **ops/s** |
| ShallowBindBenchmark.pure  |          1929.333 |   ±   | 91.018     | ops/s     |      **2016.671** | **±** | **13.878** | **ops/s** |

**Comment by vasilmkd** [comment]
| Benchmark                   |   series/3.x |       |      error | unit      |  new runtime |       |      error | unit      |
|:--------------------------- | ------------:|:-----:| ----------:|:--------- | ------------:|:-----:| ----------:|:--------- |
| AsyncBenchmark.async        |     9830.949 |   ±   |     58.232 | ops/s     | **9959.545** | **±** |  **68.475**| **ops/s** |

**Comment by wemrysi** [comment]
Host OS: Windows 10 Pro (10.0.19042 N/A Build 19042)
WSL2: Linux 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Processor: [AMD Ryzen 9 3950X (16 cores/32 threads)](https://www.amd.com/en/products/cpu/amd-ryzen-9-3950x#product-specs)
Memory: 48GB

Invocation: `benchmarks/jmh:run -i 10 -wi 10 -f 2 -t 1`
Mode: thrpt
Iteration count: 20

Benchmark                                 |  (size) |   Units | series/3.x (d2b3304) | | vasilmkd/fiber-runtime (38f23d2) | |
---|---|---|---:|---:|---:|---:
| | | |                                                             Score |   ± Error   |     Score |  ± Error
AsyncBenchmark.async                      |     100 |   ops/s |  9458.692 |  64.205    |  9462.523 | 143.486
AsyncBenchmark.bracket                    |     100 |   ops/s | 13941.220 |  63.791    | 13745.228 | 90.992
AsyncBenchmark.cancelable                 |     100 |   ops/s |  9649.511 | 135.945    | 10468.553 | 182.508
AsyncBenchmark.race                       |     100 |   ops/s | 16557.182 | 102.303    | 16466.755 | 78.043
AsyncBenchmark.racePair                   |     100 |   ops/s | 17410.875 | 104.448    | 17267.219 | 71.223
AsyncBenchmark.start                      |     100 |   ops/s |  5959.277 |  34.215    |  5670.198 | 130.572
AsyncBenchmark.uncancelable               |     100 |   ops/s | 20689.527 | 170.706    | 20849.578 | 135.351
AttemptBenchmark.errorRaised              |   10000 |   ops/s |  2051.218 |  10.871    |  2030.875 | 50.053
AttemptBenchmark.happyPath                |   10000 |   ops/s |  2781.746 |   8.195    |  2687.926 | 142.351
BothBenchmark.happyPath                   |   10000 |   ops/s |    20.635 |   0.679    |    22.283 | 0.808
DeepBindBenchmark.async                   |   10000 |   ops/s |  1460.094 |  11.803    |  1965.318 | 7.562
DeepBindBenchmark.delay                   |   10000 |   ops/s |  3550.357 |  15.208    |  3661.222 | 16.380
DeepBindBenchmark.pure                    |   10000 |   ops/s |  5170.086 |  18.335    |  4990.258 | 41.652
HandleErrorBenchmark.errorRaised          |   10000 |   ops/s |  2093.456 |   4.987    |  2135.705 | 8.899
HandleErrorBenchmark.happyPath            |   10000 |   ops/s |  2754.306 |   5.687    |  2788.967 | 11.106
MapCallsBenchmark.batch120                |     N/A |   ops/s |   216.460 |   1.220    |   216.416 | 1.430 
MapCallsBenchmark.batch30                 |     N/A |   ops/s |    56.234 |   0.431    |    55.385 | 0.391
MapCallsBenchmark.one                     |     N/A |   ops/s |     1.886 |   0.010    |     1.857 | 0.011
MapStreamBenchmark.batch120               |     N/A |   ops/s |  3829.119 |  95.937    |  3849.149 | 23.416
MapStreamBenchmark.batch30                |     N/A |   ops/s |  1608.271 |   5.066    |  1592.661 | 12.927
MapStreamBenchmark.one                    |     N/A |   ops/s |  1619.626 |  88.866    |  1620.236 | 61.812
RaceBenchmark.happyPath                   |   10000 |   ops/s |    21.364 |   0.374    |    22.511 | 0.356
RedeemBenchmark.errorRaised               |   10000 |   ops/s |  1530.740 |   4.005    |  1498.150 | 8.192
RedeemBenchmark.happyPath                 |   10000 |   ops/s |  1791.442 | 139.049    |  1916.385 | 47.221
RedeemWithBenchmark.errorRaised           |   10000 |   ops/s |  1939.238 |   4.190    |  1957.938 | 27.531
RedeemWithBenchmark.happyPath             |   10000 |   ops/s |  2647.606 |  23.632    |  2657.611 | 14.748
RefBenchmark.getAndUpdate                 |     N/A |   ops/s |  3061.660 |   7.819    |  3101.697 | 22.030
RefBenchmark.modify                       |     N/A |   ops/s |  2940.888 |   9.034    |  2998.032 | 14.496
ShallowBindBenchmark.async                |   10000 |   ops/s |  1412.736 |  13.688    |  1776.442 | 54.158
ShallowBindBenchmark.delay                |   10000 |   ops/s |  4466.638 |  13.359    |  4467.991 | 11.297
ShallowBindBenchmark.pure                 |   10000 |   ops/s |  4680.627 |  15.392    |  4749.687 | 31.011
WorkStealingBenchmark.async               | 1000000 | ops/min |    28.506 |   1.023    |           |
WorkStealingBenchmark.asyncTooManyThreads† | 1000000 | ops/min |    37.213 |   5.872 |           |
WorkStealingBenchmark.alloc               | 1000000 | ops/min |           |             |    13.093 | 0.032

† On `series/3.x` `asyncTooManyThreads` only completed 15 iterations,  failing at fork1:iteration8 and fork2:iteration9 due to java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached

On `vasilmkd/fiber-runtime` the `WorkStealingBenchmark.manyThreadsSchedulingBenchmarks` completed one warmup iteration and then appeared to stall (did not complete/make any further progress and was using no cpu).

**Comment by vasilmkd** [comment]
Yeah, `asyncTooManyThreads` is a bad benchmark, I fixed it on the new branch, we can backport the fix just to test. Thanks, these are amazing results. Do you have hyperthreading on this CPU?

**Comment by wemrysi** [comment]
Yes it has hyperthreading, so 32 threads.

**Comment by wemrysi** [comment]
@vasilmkd Updated the benchmark with results from this branch.

**Comment by vasilmkd** [comment]
Can you please run the `WorkStealingBenchmark.scheduling` from this branch? That one is `async` in the old branch. Thanks.

**Comment by vasilmkd** [comment]
`manyThreadsScheduling` stalls for me too, I hate that one.

Edit: this is indeed a bug on my part, I'm testing a fix.

**Comment by vasilmkd** [comment]
16 core/16 thread cloud VM, x86_64, Linux

| Benchmark                                   | series/3.x |     |    error | unit    | new runtime |     |    error | unit    |
|:------------------------------------------- | ----------:|:---:| --------:|:------- | -----------:|:---:| --------:|:------- |
| AsyncBenchmark.async                        |   9830.949 |  ±  |   58.232 | ops/s   |    9959.545 |  ±  |   68.475 | ops/s   |
| AsyncBenchmark.bracket                      |  10495.765 |  ±  |  139.960 | ops/s   |   10893.804 |  ±  |  125.724 | ops/s   |
| AsyncBenchmark.cancelable                   |  10384.434 |  ±  |   97.344 | ops/s   |   10396.264 |  ±  |   94.955 | ops/s   |
| AsyncBenchmark.race                         |  18189.964 |  ±  |  888.225 | ops/s   |   19361.985 |  ±  |  814.582 | ops/s   |
| AsyncBenchmark.racePair                     |  17363.516 |  ±  | 1519.836 | ops/s   |   18555.313 |  ±  | 1035.104 | ops/s   |
| AsyncBenchmark.start                        |   4063.460 |  ±  |   35.940 | ops/s   |    4083.614 |  ±  |   42.090 | ops/s   |
| AsyncBenchmark.uncancelable                 |  22145.863 |  ±  |  394.190 | ops/s   |   23396.502 |  ±  |  635.399 | ops/s   |
| AttemptBenchmark.errorRaised                |    784.957 |  ±  |   15.041 | ops/s   |     818.393 |  ±  |   12.728 | ops/s   |
| AttemptBenchmark.happyPath                  |   1068.823 |  ±  |    7.624 | ops/s   |    1086.542 |  ±  |   21.593 | ops/s   |
| BothBenchmark.happyPath                     |     11.812 |  ±  |    0.996 | ops/s   |      11.530 |  ±  |    1.212 | ops/s   |
| DeepBindBenchmark.async                     |    653.271 |  ±  |    6.336 | ops/s   |     818.714 |  ±  |   17.297 | ops/s   |
| DeepBindBenchmark.delay                     |   1640.503 |  ±  |   43.610 | ops/s   |    1682.417 |  ±  |   51.499 | ops/s   |
| DeepBindBenchmark.pure                      |   2032.309 |  ±  |   49.651 | ops/s   |    1974.248 |  ±  |   50.845 | ops/s   |
| HandleErrorBenchmark.errorRaised            |    921.365 |  ±  |    5.343 | ops/s   |     904.330 |  ±  |    9.740 | ops/s   |
| HandleErrorBenchmark.happyPath              |   1160.785 |  ±  |   21.061 | ops/s   |    1227.460 |  ±  |   17.798 | ops/s   |
| MapCallsBenchmark.batch120                  |    261.038 |  ±  |    5.769 | ops/s   |     284.736 |  ±  |    3.056 | ops/s   |
| MapCallsBenchmark.batch30                   |     72.020 |  ±  |    1.864 | ops/s   |      75.910 |  ±  |    2.822 | ops/s   |
| MapCallsBenchmark.one                       |      2.480 |  ±  |    0.078 | ops/s   |       2.647 |  ±  |    0.047 | ops/s   |
| MapStreamBenchmark.batch120                 |   1921.262 |  ±  |   94.059 | ops/s   |    1991.106 |  ±  |   48.510 | ops/s   |
| MapStreamBenchmark.batch30                  |    728.545 |  ±  |    7.357 | ops/s   |     736.125 |  ±  |   19.731 | ops/s   |
| MapStreamBenchmark.one                      |    762.429 |  ±  |   11.015 | ops/s   |     752.227 |  ±  |   15.598 | ops/s   |
| RaceBenchmark.happyPath                     |     11.069 |  ±  |    1.097 | ops/s   |      12.062 |  ±  |    0.907 | ops/s   |
| RedeemBenchmark.errorRaised                 |    560.077 |  ±  |    7.253 | ops/s   |     568.534 |  ±  |    4.096 | ops/s   |
| RedeemBenchmark.happyPath                   |    774.793 |  ±  |   16.296 | ops/s   |     771.138 |  ±  |    7.947 | ops/s   |
| RedeemWithBenchmark.errorRaised             |    732.959 |  ±  |   18.496 | ops/s   |     732.736 |  ±  |    7.212 | ops/s   |
| RedeemWithBenchmark.happyPath               |    997.860 |  ±  |   41.992 | ops/s   |     977.828 |  ±  |   11.662 | ops/s   |
| RefBenchmark.getAndUpdate                   |   1318.607 |  ±  |   45.739 | ops/s   |    1325.232 |  ±  |   11.450 | ops/s   |
| RefBenchmark.modify                         |   1295.695 |  ±  |   21.721 | ops/s   |    1205.523 |  ±  |   46.815 | ops/s   |
| ShallowBindBenchmark.async                  |    630.894 |  ±  |    3.108 | ops/s   |     793.133 |  ±  |    9.212 | ops/s   |
| ShallowBindBenchmark.delay                  |   1657.195 |  ±  |   39.486 | ops/s   |    1683.985 |  ±  |   22.624 | ops/s   |
| ShallowBindBenchmark.pure                   |   1976.363 |  ±  |   50.396 | ops/s   |    1992.983 |  ±  |   26.092 | ops/s   |
| WorkStealingBenchmark.alloc                 |      5.442 |  ±  |    0.051 | ops/min |       5.434 |  ±  |    0.111 | ops/min |
| WorkStealingBenchmark.manyThreadsScheduling |     16.917 |  ±  |    0.836 | ops/min |      17.539 |  ±  |    1.186 | ops/min |
| WorkStealingBenchmark.scheduling            |     14.799 |  ±  |    1.419 | ops/min |      16.208 |  ±  |    1.417 | ops/min |

Baseline, fixed thread pool:
0.660 ops/min

**Comment by wemrysi** [comment]
`WorkStealingBenchmark` results from 220d010

Host OS: Windows 10 Pro (10.0.19042 N/A Build 19042)
WSL2: Linux 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Processor: AMD Ryzen 9 3950X (16 cores/32 threads)
Memory: 48GB

Benchmark                                             |  (size) |  Mode | Cnt |  Score | | Error |   Units
---|---|---|---|---|---|---|---
WorkStealingBenchmark.alloc                           | 1000000 | thrpt |  20 | 13.172 |±| 0.110 | ops/min
WorkStealingBenchmark.manyThreadsSchedulingBenchmarks | 1000000 | thrpt |  20 | 46.493 |±| 3.439 | ops/min
WorkStealingBenchmark.scheduling                      | 1000000 | thrpt |  20 | 50.033 |±| 3.891 | ops/min

**Comment by vasilmkd** [comment]
@djspiewak Holy shit...

**Comment by vasilmkd** [comment]
```
series/3.x
WorkStealingBenchmark.async | 1000000 | ops/min | 28.506 | 1.023
```

```
new runtime
WorkStealingBenchmark.scheduling | 1000000 | thrpt | 20 | 50.033 | ± | 3.891 | ops/min
```

This is the exact same benchmark, I just renamed it...

**Comment by djspiewak** [comment]
What the fuck…? How on earth?! That's a monster insane jump.

**Comment by vasilmkd** [comment]
Game plan for merging this PR into `series/3.x`:
- [x] `LocalQueue` (simplified and well documented version of `WorkStealingQueue`) #1711
- [x] `BlockingThread` (`WorkStealingThreadPool extends BlockContext`) #1734 
- [x] Refactoring of `WorkStealingThreadPool` and `WorkerThread` #1764
- [x] Performance improvements everywhere #1764
- [ ] MBeans

**Comment by vasilmkd** [comment]
All code (and more) from this PR has been merged as parts of #1711, #1734 and #1764.

**Pull request closed without merging**
