### PR TITLE
Add LiftIO.liftK, Effect.toIOK

### PR DESCRIPTION
**Pull request by nigredo-tori**
As proposed by @Daenyth in #465.

### CODE REVIEW

**Comment by nigredo-tori** [comment]
> Wouldn't mind seeing the corresponding one for `Effect`

Done. Called it `toIOK` to minimize confusion.

**Comment by rossabaker** [comment]
But I would love to see a test if we can write one that doesn't just parrot the implementation.

**Comment by nigredo-tori** [comment]
> But I would love to see a test if we can write one that doesn't just parrot the implementation.

I'm not sure what that should check, then, since the implementation is just building a `FunctionK`. I can't think of anything other than `ioa.to[F] <-> LiftIO.liftK[F].apply(ioa)`, and that tests kindprojector more than anything.

**Comment by rossabaker** [comment]
I can't think of an interesting test either.  We'll see if someone else does, but it has my approval.

**Pull request merged**
