### PR TITLE
WIP: Unexceptional IO and type classes

### PR DESCRIPTION
**Pull request by LukaJCB**
This is a WIP I started some time ago to address #176 as well as #67. It adds a newtype for `IO` called `UIO` that's taken from what I created in `cats-uio`.
I recognize there is no consensus on this issue at all, but I had this WIP on my computer for a while and wanted to maybe restart discussion around it. 
I still strongly believe this would be a valuable addition to this project, but also realize that we're adding a lot of stuff that makes the hierarchy a tad more complex.

I think this is a fully source compatible change, but it's probably not binary compatible, which is unfortunate.

### CODE REVIEW

**Comment by rossabaker** [comment]
It has been proposed in a few places that `BIO[E, A]` generalizes `IO[A]` and `UIO[A]`.  I disagree that `IO[A] = BIO[Throwable, A]` because of catching from `map` and `flatMap`.  

Does `UIO[A] = BIO[Nothing, A]`?  The typeclass hierarchy is different, without `MonadError` and `Bracket`.  But what about the type itself?

**Comment by LukaJCB** [comment]
The type `UIO[A]` is indeed isomorphic to `BIO[Nothing, A]`, yes :)

**Comment by rossabaker** [comment]
My question is, why this and not an alias to `BIO`?  Just as a negative type to shed the useless `ApplicaitveError` instance we'd otherwise have?

**Comment by LukaJCB** [comment]
That is indeed a very good question. 
I'd argue a newtype over `BIO` costs us about the same as a newtype over `IO`.
That said, `BIO`'s future is unclear and I think working with a single type parameter is vastly more ergonomic in Scala, as it allows us to work with context bounds and works easily with tons of code already written with an abstract `F[_]`. Moreover working with `Nothing` on the left hand side is really uncomfortable and the Scala compiler will fight you along the way. We could introduce something like `Void`, but I'm not sure it makes things that much easier.
Right now, I can use `IO` in conjunction with `UIO` with zero cost when converting from one to the other and working with it for close to 2 months, it's been pretty nice so far. 

If we decide #197 has a future in `cats-effect` I'm happy to close this in favor of that one, though I'm not yet fully convinced myself. :)

**Comment by LukaJCB** [comment]
Just looked at the merge conflicts, and I think we could see some immediate benefits, as we could make `Ref` unexceptional and `Deferred` as well if we offer a version that doesn't throw an error on the second `complete` call :)

**Comment by alexandru** [comment]
I think unexceptional type classes is the wrong approach. We're probably going to need "bifunctor" type classes. Open to proposals.

Will close this for now.

**Pull request closed without merging**
