### PR TITLE
Add `The Case For Effect Systems` talk

### PR DESCRIPTION
**Pull request by lenguyenthanh**

### CODE REVIEW

**Comment by armanbilge** [comment]
@lenguyenthanh do you mind to re-target at `series/3.5.x`? otherwise it won't go live on the site for a while. thanks!

**Comment by lenguyenthanh** [comment]
> @lenguyenthanh do you mind to re-target at `series/3.5.x`? otherwise it won't go live on the site for a while. thanks!

No, not at all. But it seems I did something wrong when I changed the base from `3.x` to `series/3.5.x`.
Maybe it should be a new commit from `series/3.5.x`?

**Comment by armanbilge** [comment]
Yes,  you need to do a rebase. Because this branch has all the series/3.x commits on it. Or just create a new branch/PR 😅

**Comment by lenguyenthanh** [comment]
ah, I thought github is smart enough to rebase for me lol. I'll rebase locally later today.

**Comment by lenguyenthanh** [comment]
I have to admit, it's easier to just cherry pick 😂 
superseded by #3905

**Pull request closed without merging**
