### PR TITLE
Update formatting of ScalaDoc examples

### LINKED ISSUE #2797: Fix scaladoc formatting issues
It appears that scalafmt is pretty aggressively breaking a lot of scaladoc. We need to go back through and fix it, then probably wrap in `noformat` to prevent it from breaking again.

### PR DESCRIPTION
**Pull request by iRevive**
Minor improvements of the readability.

### Before
before

### After
after

### CODE REVIEW

**Review by armanbilge — DISMISSED** [review]
Thanks, looks much better!

Closes https://github.com/typelevel/cats-effect/issues/2797 assuming this was all of them?

**Comment by armanbilge** [comment]
Oh btw, if you are able to retarget your PR to series/3.3.x branch then it will be released/published online more quickly.

**Comment by iRevive** [comment]
There are a few more, unfortunately. 

scalafmt is pretty aggressive when it comes down to wrapping. For example, it can force a break inside of back-ticked expression:
```scala
/**
  * Relatively long comment line that exceeds 'maxColumn' limit: `a /
  * b`
  */
```

Ideally, it should be formatted as:
```scala
/**
  * Relatively long comment line that exceeds 'maxColumn' limit: 
  * `a / b`
  */
```

I can experiment with [docstring.wrap = no](https://scalameta.org/scalafmt/docs/configuration.html#docstringswrap).

The docs will not be unified and it will be up to authors to follow the most common formatting (the same way it was before scalafmt 2.6)

**Comment by iRevive** [comment]
The target branch cannot be `series/3.3.x`, since the branch depends on some upstream commits ([0b391cdeb00499e97848069826450dbe30001260](https://github.com/typelevel/cats-effect/commit/ec0c339804a48fa4600725f0d8740a9ece6c3c61), for instance).

**Comment by armanbilge** [comment]
Ah, I see. Thanks for trying!

**Review by armanbilge — APPROVED** [review]

**Review by djspiewak — APPROVED** [review]
Thank you!

**Pull request merged**
