### PR TITLE
Remove unused Eq[IO[Either[F[A], A]]] from EffectTests

### PR DESCRIPTION
**Pull request by rossabaker**
As long as we're breaking binary compatibility in laws, we can eliminate two warnings with this.

### CODE REVIEW

**Comment by rossabaker** [comment]
Build is failing on JDK 11 install.

**Comment by djspiewak** [comment]
Merge with master?

**Comment by rossabaker** [comment]
I don't know whether our policy is to force-push or merge.  Sorry to the half of you I enraged.

This pulls in #518 and should green it up.

**Comment by djspiewak** [comment]
😡

**Pull request merged**
