### PR TITLE
Add code of conduct

### PR DESCRIPTION
**Pull request by kubukoz**
I realized it was missing in series/3.x, so I'm adding one - as suggested by Alex on discord I added @djspiewak too

### CODE REVIEW

**Review by rossabaker — APPROVED** [review]

**Review by vasilmkd — APPROVED** [review]

**Comment by alexandru** [comment]
👍

@kubukoz you should add a `CONTRIBUTING.md` too 🙂

Didn't we have one? Here's [the one from Monix](https://github.com/monix/monix/blob/series/4.x/CONTRIBUTING.md) for inspiration.

**Comment by alexandru** [comment]
Can be a separate PR 🙂

**Review by alexandru — APPROVED** [review]

**Comment by aeons** [comment]
Maybe have discord references instead of gitter, if that is the new official communication channel?

**Comment by djspiewak** [comment]
:+1: for Discord references (is that possible?) but overall this is excellent. I'll merge for now so we don't hold it up, and we should come back to it and adjust if we can figure out how to make those direct links.

**Pull request merged**
