### PR TITLE
Use platform-dependent implementation of Clock.realTime

### PR DESCRIPTION
**Pull request by sergeykolbasov**
As discussed in #1460

### CODE REVIEW

**Comment by sergeykolbasov** [comment]
@djspiewak Hello, any thoughts on this?

**Comment by djspiewak** [comment]
Sorry! This somehow fell off my radar in the shuffle. This looks very good! Would you be interested in looking into bringing these improvements to the `series/3.x` branch as well?

**Comment by sergeykolbasov** [comment]
No problem.

Sure can do for 3.x, although last time I checked there was no actual implementation of clocks there. Is it supposed to be the same?

**Comment by djspiewak** [comment]
Clock is defined as a typeclass, and the implementation is in IO and SyncIO (in CE3). 😃 Just a reorganization, not a removal.

**Pull request merged**
