### PR TITLE
Fix typo in tutorial.md

### PR DESCRIPTION
**Pull request by moleike**
It should say `delay` instead of `blocking`

### CODE REVIEW

**Comment by vasilmkd** [comment]
I'm sorry, I do believe that the example is indeed correct as it is. `InputStream` and `OutputStream` are the Java blocking I/O APIs and `IO.blocking` accurately wrap the blocking side-effectful calls that are `InputStream#read` and `OutputStream#write`.

**Comment by vasilmkd** [comment]
You can read more about it [here](https://typelevel.org/cats-effect/docs/typeclasses/sync). Unfortunately, we are still working on the `IO` specific documentation.

**Comment by moleike** [comment]
My bad, I assumed it was `delay` based on the preceding paragraph:

> replacing any use of `IO` by calls to the `delay` and `pure` methods of the
`Sync[F]` instance:

Thanks for your quick reply, @vasilmkd!

**Comment by vasilmkd** [comment]
That's a good observation. Do you mind changing this PR to revert the code change and instead fix the paragraph text? Thanks. 😄

**Comment by vasilmkd** [comment]
Closing this one, feel free to follow up on what we discussed above in a new PR.

**Pull request closed without merging**
