### PR TITLE
WIP: Add SyncVar

### PR DESCRIPTION
**Pull request by johnynek**
What do you all think of including something like this?

Seems useful to me to interop with State in a nice way.

I can add tests and polish if the direction looks sane.

### CODE REVIEW

**Comment by mpilquist** [comment]
I've lobbied before for pulling in `fs2.async.Ref` (https://github.com/functional-streams-for-scala/fs2/blob/series/0.10/core/shared/src/main/scala/fs2/async/Ref.scala). Very similar but `Ref` has more derived operations (of particular note is `access`).

Perhaps more controversially, I'd like to see `fs2.async.Promise` or an `MVar` type.

**Comment by johnynek** [comment]
Modulo some minor bike-shedding (prefer not to capture the Sync instance in the class), I’d be in favor of bringing these in.

**Comment by rossabaker** [comment]
I don't think we've done a good job establishing principles for what's in scope and what's not.

Thinking out loud:
1. Is it necessary to support the core typeclasses?
2. Are the differences in downstream implementations cosmetic rather than tradeoffs?
3. Is it frequent in public API so that its inclusion promotes interop downstream?
4. Is it useful in implementing another type that satisfies the above?
5. ???

I think it's useful, but can we justify it with any of the above?

**Comment by rossabaker** [comment]
My argument for exclusion is that all public API is a liability for compatibility and this is a bedrock project that demand stability.  My argument for inclusion is that we're just passing that liability downstream and multiplying it.  I'm leaning toward inclusion here.

Since we're having a lot of in-or-out debates lately (this, Resource, Exec, generic TaskApp), I just thought it would be a good time to establish some principles to guide these debates.

**Comment by LukaJCB** [comment]
I agree that something like this should have a place in `cats-effect` :+1:

**Comment by mpilquist** [comment]
I'm 👍 on `Ref` being added to cats-effect. I'll defer discussion on `Promise` to another time and another issue. I'm generally pretty :-1: on a new project like cats-concurrent. I'm not convinced that adding more modules simplifies things for anyone.

**Comment by alexandru** [comment]
Well, if we are voting, I’m :+1: on an `MVar` and :-1: on a `Promise` ... well, the one in fs2 seemed too complicated, but I’m talking of the one meant for cats-effect pre-0.10.

I can contribute the `MVar`, have a pretty good one in Monix, but it might need some changes.

Speaking of which, in Monix I’ve got enhanced `Atomic` types and having the ability to provide a better implementation is valuable.

So in case we provide a `SyncVar`, which I’d name `Ref`, I think I’d leave different implementations possible. You know, the way we defined `Timer`, we could have that as a sealed trait too, but it’s cool that in Monix I can come up with a different implementation that plays to `Task`’s strength.

**Comment by rossabaker** [comment]
Would `Concurrent` and `ConcurrentEffect` belong in cats-effect or cats-concurrent?  I would think the latter, but then monix and fs2 and things downhill of those still need a stable cats-concurrent and we've not solved anyone's problem.

Otherwise, I'd brand the second project as the cats-effect-contrib proposed elsewhere, and I'm a mild :-1: on that.  I'm :+1: on this in cats-effect-1.x, for whatever x it's ready and compatible, but not blocking 1.0 for it.

**Comment by oleg-py** [comment]
I have seen demand for a pure mutable primitive like Ref or Promise pop up 1-2 times a week for a while already. While it's good that fs2 has them, it's kinda odd that we have to point out people to a streaming library. Hell, I've been using fs2 on a personal project for a couple of months and had no idea that it had these.

I think it's reasonable to expect such demand to increase, and I think cats ecosystem should provide a solution other than `¯\_(ツ)_/¯`. These things (Ref, Promise, MVar, Semaphore) are super useful from an application developer's standpoint, and there are other things that I'd rather have a go-to solution for (converting from java Futures, memoization, SafeApp).

The scope of that is probably different from the scope of `cats-effect`, at least the currently agreed on, which is why a separate project makes sense IMO.

**Comment by johnynek** [comment]
I think it can be scary use-at-own risk for now. I don't think modules have to have the same compatibility guarantees. In fact, we can easily mima only a subset of the jars, or better yet, be more generous giving exclusions.

**Comment by mpilquist** [comment]
If `Ref`/`Promise` were extracted from FS2, combined with other implementations, etc., FS2 will need them to be stable. On each breaking change, FS2 would need to be rebuilt, which then cascades through doobie, http4s, and a bunch of other projects. So while we can call the APIs provisional, in practice, a breaking change will cause the entire ecosystem depending on FS2 to be rebuilt.

I totally agree on the costs of a separate project but I don't really buy the JAR size argument given we are talking about < 10 types. My strong preference is to include such types directly in cats-effect under a `cats.effect.concurrent` package modulo package name.

**Comment by rossabaker** [comment]
That strategy sounds fine in application use.  For libraries, the compatibility promise is no stronger than  that of the subprojects they pull in transitively.  Wouldn't this destabilize fs2, monix, and every library downstream?

No, I can't switch to bazel yet. :stuck_out_tongue:

**Comment by alexandru** [comment]
Just one note — the quality threshold for `cats-effect` has to be higher.

For example if I am to import [MVar](https://github.com/monix/monix/blob/master/monix-eval/shared/src/main/scala/monix/eval/MVar.scala) from Monix, then something like `def read: F[A]` is under question because it's not an atomic operation and the only reason it exists is as an optimization over `take.flatMap(a => put(a).map(_ => a))`. The current implementation doesn't do cancelation either because I did not see a point, but that might need to change (not a problem, must mentioning it).

Looking at `Ref` from fs2, it's pretty cool but I'm not sure I see the point of something like `tryModify`. It's better if we are a little conservative, because it's harder to remove things later.

That said I'm 👍 for going forward with this. Lets do just a package for now, named `cats.effect.concurrent` or something — I prefer at least a separate package in case we ever think of splitting the project in two later.

**Comment by mpilquist** [comment]
@alexandru That sounds good to me. One reservation though - moving `Ref` and `Promise` from `fs2.async` to `cats.effect.concurrent` is an API breaking change to FS2 (which we can perhaps mitigate with some type aliases assuming the methods don't change too drastically). We were planning on releasing FS2 1.0 once cats-effect 1.0 was out but with this pending change, we'd have to delay FS2 1.0 until cats-effect 1.1. Hence, no cancelation, bracketing, or timers for FS2 users until cats-effect 1.1. We could release FS2 0.11 against cats-effect 1.0 and then release FS2 1.0 once we have cats-effect 1.1 but doing so requires the entire downstream ecosystem to rebuild/republish twice in relatively short order. If instead we pulled `Ref` and `Promise` in to 1.0, FS2 1.0 could occur just after cats-effect.

**Comment by mpilquist** [comment]
> Looking at Ref from fs2, it's pretty cool but I'm not sure I see the point of something like tryModify. It's better if we are a little conservative, because it's harder to remove things later.

Indeed, we don't use it anymore in FS2 itself but some clients do. Perhaps @pchlupacek could grep some of his code for some examples.

**Comment by pchlupacek** [comment]
I don't think so we use `tryModify`. I think it was before Semaphore was introduced in the fs2, with Semaphore you essentially do not have need for it. 

As a note, I am very conservative about breaking change between 0.10 and 1.0 of fs2 because fs2 is contributing the Promise and Ref to cats effects.  Could we perhaps get it in 1.0 are we really under such pressure? FOr those waiting on final, can they be happy with RCx release of the cats effects?

**Comment by mpilquist** [comment]
I'll prepare a basic PR today which we can use as a starting point. Let's see how much progress we can make on it before 5/15.

**Pull request closed without merging**
