### PR TITLE
Fix scala versions in mergify

### PR DESCRIPTION
**Pull request by kubukoz**

### CODE REVIEW

**Review by vasilmkd — APPROVED** [review]

**Comment by kubukoz** [comment]
That's weird...

```
[info]   + exit on fatal error
[error]   x exit on fatal error with other unsafe runs
[error]    java.lang.NullPointerException
[error]    	at cats.effect.unsafe.WorkStealingThreadPool.notifyParked(WorkStealingThreadPool.scala:198)
[error]    	at cats.effect.unsafe.WorkStealingThreadPool.executeFiber(WorkStealingThreadPool.scala:343)
[error]    	at cats.effect.unsafe.WorkStealingThreadPool.execute(WorkStealingThreadPool.scala:369)
[error]    	at cats.effect.IOFiber.blockingR(IOFiber.scala:1094)
[error]    	at cats.effect.IOFiber.run(IOFiber.scala:136)
[error]    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]    	at java.lang.Thread.run(Thread.java:748)
[error]    java.lang.NullPointerException
[error]    	at cats.effect.unsafe.WorkStealingThreadPool.notifyParked(WorkStealingThreadPool.scala:198)
[error]    	at cats.effect.unsafe.WorkStealingThreadPool.executeFiber(WorkStealingThreadPool.scala:343)
[error]    	at cats.effect.unsafe.WorkStealingThreadPool.execute(WorkStealingThreadPool.scala:369)
[error]    	at cats.effect.IOFiber.blockingR(IOFiber.scala:1094)
[error]    	at cats.effect.IOFiber.run(IOFiber.scala:136)
[error]    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]    	at java.lang.Thread.run(Thread.java:748)
[error]    Exception in thread "main" java.lang.NullPointerException
[error]    	at cats.effect.unsafe.WorkStealingThreadPool.notifyParked(WorkStealingThreadPool.scala:198)
[error]    	at cats.effect.unsafe.WorkStealingThreadPool.executeFiber(WorkStealingThreadPool.scala:343)
[error]    	at cats.effect.unsafe.WorkStealingThreadPool.execute(WorkStealingThreadPool.scala:369)
[error]    	at cats.effect.IOFiber.blockingR(IOFiber.scala:1094)
[error]    	at cats.effect.IOFiber.run(IOFiber.scala:136)
[error]    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]    	at java.lang.Thread.run(Thread.java:748)
```

**Comment by vasilmkd** [comment]
Could this be a bug with Dotty M3? Seriously, that object should have been initialized in the class constructor...

**Comment by djspiewak** [comment]
It's possibly a bug with Dotty but we should trace it through to be sure.

**Comment by vasilmkd** [comment]
@kubukoz Do you mind rebasing this PR. The issue has been fixed. Thank you.

**Comment by kubukoz** [comment]
@mergifyio rebase

**Pull request merged**
