### PR TITLE
Invariant for dequeue

### PR DESCRIPTION
**Pull request by TimWSpence**

### CODE REVIEW

**Comment by TimWSpence** [comment]
@djspiewak as requested :)

**Review by vasilmkd — APPROVED** [review]

**Comment by vasilmkd** [comment]
Are there laws for Invariant that we can use?

**Comment by TimWSpence** [comment]
@vasilmkd yup https://github.com/typelevel/cats/blob/master/laws/src/main/scala/cats/laws/InvariantLaws.scala

I was just lazy because none of the other `{Co, Contra, In}variant` instances for the queues check the laws and it seems pretty obvious that they are satisfied 😂 

We probably should check them 😭

**Comment by vasilmkd** [comment]
That could be a nice first issue.

**Comment by TimWSpence** [comment]
> That could be a nice first issue.

Good call! :) I created https://github.com/typelevel/cats-effect/issues/1618 but can't tag it with first issue or ce3

**Pull request merged**
