### PR TITLE
WIP: Enable Unidoc

### PR DESCRIPTION
**Pull request by alexandru**
Trying to enable the unidoc plugin, unfortunately it fails currently.

I'm creating the PR, then opening an issue on unidoc's repo.

The error I'm seeing:

```
> unidoc
[info] Compiling 9 Scala sources to cats-effect/core/jvm/target/scala-2.12/classes...
[info] Main Scala API documentation to cats-effect/target/scala-2.12/unidoc...
[error] Symbol 'type cats.effect.Effect.ToEffectOps' is missing from the classpath.
[error] This symbol is required by 'package cats.effect.implicits.package'.
[error] Make sure that type ToEffectOps is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
[error] A full rebuild may help if 'package.class' was compiled against an incompatible version of cats.effect.Effect.
[info] No documentation generated with unsuccessful compiler run
[error] one error found
[error] (root/scalaunidoc:doc) Scaladoc generation failed
[error] Total time: 9 s, completed Apr 24, 2017 11:04:43 PM
```

I've opened the issue at: https://github.com/sbt/sbt-unidoc/issues/35

### CODE REVIEW

**Comment by djspiewak** [comment]
Cool, ty.  As a random methodology FYI, since this PR is marked as "WIP", I'm ok with rebasing at your discretion.

**Comment by alexandru** [comment]
I opened the issue on the `sbt-unidoc` issue tracker.

@djspiewak I think we should disable `Xfatal-errors` on normal `doc` and (assuming we enable Unidoc) to leave that on only for `unidoc`, which should run in Travis only for the "main" Scala version.

I already did that in this PR, which is why the Travis build is failing only for Scala 2.11: 
https://travis-ci.org/typelevel/cats-effect/builds/225355929

**Comment by djspiewak** [comment]
@alexandru Disabling `-Xfatal-errors` for `doc` seems perfectly reasonable.

**Comment by rossabaker** [comment]
I've used and endorse that disabling.

**Comment by alexandru** [comment]
Status: I haven't figured out how to fix this and nobody responded yet on https://github.com/sbt/sbt-unidoc/issues/35

**Comment by alexandru** [comment]
Haven't been able to make progress on this PR and there's no use in keeping it around, so closing it.

**Pull request closed without merging**
