### PR TITLE
Disable JS tracing in production

### PR DESCRIPTION
**Pull request by armanbilge**
Implicitly addresses #2285. See also https://github.com/typelevel/cats-effect/discussions/2221#discussioncomment-1260630.

### CODE REVIEW

**Comment by vasilmkd** [comment]
This looks good to me. Before I press approve though, didn't you discuss that `fullOptJS` and source maps should be traced? This change seems to not support that? Sorry if this is an obtuse question.

**Comment by armanbilge** [comment]
You're right, we're going back on our previous decision. See https://discord.com/channels/632277896739946517/839263556754472990/889877834150068244

In an ideal world, we'd find a way to support fullOpt/sourcemaps. But the advantage of totally disabling tracing for fullOpt is that it can be dead-code-eliminated.

**Comment by vasilmkd** [comment]
Yes, good. I'm all for it.

**Review by vasilmkd — APPROVED** [review]

**Comment by djspiewak** [comment]
Let's do it and wait for the complaints to roll in. :-D It's easier to add functionality later than it is to go back on functionality we've already shipped.

**Pull request merged**
