### PR TITLE
Port concurrent deferred

### PR DESCRIPTION
**Pull request by TimWSpence**
Note that this removes the `uncancelable` versions of `Deferred` as we no longer have the `Concurrent`/`Async` distinction where one supports cancellation and the other doesn't.

### CODE REVIEW

**Comment by TimWSpence** [comment]
For CE3 @djspiewak :)

**Comment by TimWSpence** [comment]
Also please don't judge that commit history 😂

**Comment by djspiewak** [comment]
:-D I don't say this often, but it's probably worth squashing the wips away. I generally try to do that before I push.

**Comment by TimWSpence** [comment]
@djspiewak I assumed you squash on merge? If not then yes, I definitely will!!

**Comment by djspiewak** [comment]
> I assumed you squash on merge?

Nope. :-) Generally speaking, when something is in a PR, I consider it sacred and I won't rebase or squash those commits.

**Comment by TimWSpence** [comment]
Then I will be a LOT more careful in future! 😂 I've squashed the WIP mess at least now

**Comment by djspiewak** [comment]
I really need to get the import warnings working on 2.13 and Dotty… Sorry about that…

**Pull request merged**
