### PR TITLE
Add Arman to the list of developers and change the Twitter handles to email addresses

### LINKED ISSUE #2328: Maven developer metadata expects emails, not Twitter handles
https://search.maven.org/artifact/org.typelevel/cats-effect_2.13

Are people in favor of changing this? I am.

### PR DESCRIPTION
**Pull request by vasilmkd**
Resolves #2328.

### CODE REVIEW

**Comment by vasilmkd** [comment]
I did not add email addresses for @RaasAhsan and @SystemFw because there was nothing there originally. Let me know if I should change this.

Tagging the other people on the developers list to check their email addresses or to speak up if I should remove them.
@djspiewak @TimWSpence @kubukoz @mpilquist @bplommer @wemrysi @armanbilge @gvolpe 

I got the email addresses from `git log`.

**Review by djspiewak — DISMISSED** [review]

**Comment by kubukoz** [comment]
can't wait for the bots to dig through the repo :D 

edit: but then I guess, they could always do that with `git log`

**Comment by djspiewak** [comment]
@kubukoz Yeah Git leaks emails by definition, so it doesn't make a difference. :-)

Honestly, my email has been just publicly posted exactly as-written for more than 15 years, and at the end of the day, you have to trust the spam filters. I haven't regretted making myself easier to contact.

**Comment by SystemFw** [comment]
You can add mine, it's already out there :P https://github.com/typelevel/kittens/blob/master/CONTRIBUTORS

**Review by djspiewak — APPROVED** [review]

**Pull request merged**
