### PR TITLE
Remove unused code

### PR DESCRIPTION
**Pull request by durban**
It's private, and nothing uses it.

### CODE REVIEW

**Review by armanbilge — APPROVED** [review]
thanks!

**Comment by armanbilge** [comment]
oh, actually whenever you change the base branch, you have to re-trigger CI. the current ✅ is based on CI running against 3.x, not 3.5.x

**Comment by durban** [comment]
Huh, great. Cirrus didn't seem to restart with the close/open, so I tried to restart it manually. I don't know if I succeeded...

**Comment by armanbilge** [comment]
Ah, actually Cirrus doesn't need to be restarted anyway ...

So the difference is that GHA CI runs on a synthetic merge commit. So for example, the initial CI run was on 4ef1966c2f86460922ad7216ebbee0cb025260df which merged in `series/3.x`. The close-reopen dance causes CI to run on a new merge commit bfd7630c3579c69b8d4126c35cb98b9ca38483d4, this time with `series/3.5.x`.

Meanwhile, Cirrus runs CI on the branch itself, not a synthetic merge commit. So in both cases it is running on 907b121665c7de6dd7bfd019693c7188bab12109, it doesn't matter which branch the PR is targeting.

**Pull request merged**
