### PR TITLE
Scala and GraalVM version updates

### PR DESCRIPTION
**Pull request by vasilmkd**
Warming up the planet using the latest Scala and GraalVM.

### CODE REVIEW

**Comment by vasilmkd** [comment]
@djspiewak, @RaasAhsan can you please check this PR very carefully. I'm especially curious about the unused functor instances for the `std` functor derivations, it seems the underlying `F[_]` does not explicitly need to be a `Functor` itself, but maybe this was an intentional constraint? If that was indeed the case, I apologize.

**Review by djspiewak — APPROVED** [review]
Incidentally this is breaking binary compatibility. Still worth it I think.

**Comment by djspiewak** [comment]
I'm inclined to trust the compiler on this one. It does indeed seem that the constraints were unnecessary.

**Comment by vasilmkd** [comment]
Oh yeah totally binary compatibility breaking, I forgot to mention...

**Pull request merged**
