### PR TITLE
Fix flaky test

### PR DESCRIPTION
**Pull request by armanbilge**
Tries to make the test from #2665 less flaky. Open to ideas.

### CODE REVIEW

**Review by vasilmkd — COMMENTED** [review]
Is it perhaps simpler to encode this as a `gate: Deferred[Unit]` with the main fiber calling `gate.get` and the `CompletableFuture` running `gate.complete(())`?

It's the same on the surface.

**Review by djspiewak — DISMISSED** [review]

**Comment by armanbilge** [comment]
Strange, it flaked again!
```
 [info] AsyncPlatform CompletableFuture conversion should
[error]   x cancel CompletableFuture on fiber cancelation
[error]    Expected: java.util.concurrent.CancellationException. Got nothing (AsyncPlatformSpec.scala:40)
```

**Comment by armanbilge** [comment]
Ouch, flaked again :woozy_face:

**Comment by armanbilge** [comment]
OTOH, https://github.com/typelevel/cats-effect/pull/2669 has passed three times in a row.

**Pull request closed without merging**
