### PR TITLE
Revert PQueue FIFO priority ties

### PR DESCRIPTION
**Pull request by SystemFw**
See #2298

### CODE REVIEW

**Review by vasilmkd — COMMENTED** [review]
LGTM with pending formatting and a CI run. 😄

**Comment by vasilmkd** [comment]
A general project management question, does this PR essentially undo the work that started the `series/3.2.x` branch (minus the new comments in this PR)?

**Comment by SystemFw** [comment]
>  does this PR essentially undo the work that started the series/3.2.x branch

Yes, and actually I wasn't fully sure what the best way of going about it was. I reverted changes and 3.2.x, but not 100% confident that's the way to go

**Comment by TimWSpence** [comment]
LGTM! 👍

**Review by djspiewak — APPROVED** [review]

**Pull request merged**
