### PR TITLE
Undo workarounds for `bitmap$init`

### PR DESCRIPTION
**Pull request by armanbilge**
Don't feel strongly about this, but I think the old code was just a little cleaner and better scoped. I think these were the only two places?

### CODE REVIEW

**Comment by vasilmkd** [comment]
This is not a workaround, this is actual functionality. When blocking occurs, a new worker thread is spawned that replaces the blocked one. When the blocked one finishes, it dies. The fiber bag needs to be transferred from the old thread to the replacement thread, otherwise we lose references to fibers. Please remove that commit. You can restore the `blocking = false`.

**Comment by armanbilge** [comment]
Woops! That makes more sense. Your commit messages were plenty clear enough on that fact to make me stare hard at it, but that doesn't get the brain working 😉

**Comment by vasilmkd** [comment]
The `blockedWorkerThreadCounterForwarder` is ok to remove.

**Comment by vasilmkd** [comment]
Can you please remove the commits and force push?

**Comment by armanbilge** [comment]
This one strikes again for windows/graalvm:
```
[info] IOAppSpec
[info] IOApp (jvm) should
[error]   x evaluate and print hello world
[error]    1 != 0 (IOAppSpec.scala:39)
[error]   x pass all arguments to child
[error]    1 != 0 (IOAppSpec.scala:46)
```

**Review by vasilmkd — APPROVED** [review]
Nice cleanup.

**Pull request merged**
