### PR TITLE
fix typo in tutorial

### PR DESCRIPTION
**Pull request by vgrigoriu**

### CODE REVIEW

**Comment by durban** [comment]
Could you merge [series/3.x](https://github.com/typelevel/cats-effect/tree/series/3.x) into this branch? It seems to be necessary to make CI green. Thanks!

**Comment by armanbilge** [comment]
Merging not necessary actually, the close/re-open should do the trick :)

**Review by durban — DISMISSED** [review]

**Comment by armanbilge** [comment]
Actually same with this one, we can retarget this PR to `series/3.5.x`. Otherwise it will not be released for a while.

**Comment by vgrigoriu** [comment]
Done.

**Pull request merged**
