### PR TITLE
Bye bye helper thread

### PR DESCRIPTION
**Pull request by vasilmkd**
I chose violence.

> “I didn't have time to write a short letter, so I wrote a long one instead.”
&ndash; Mark Twain

### CODE REVIEW

**Comment by vasilmkd** [comment]
Comments, further tests with `fs2`, a snapshot to test possible regressions against `munit-cats-effect`, benchmarks incoming, as per usual.

**Comment by vasilmkd** [comment]
Tasks:

- [x] `publishLocal` and test against `fs2` (run the tests 10 times)
- [x] publish a snapshot (`"io.vasilev" %%% "cats-effect" % "3.3-170-56db84c"`)
- [x] test against `munit-cats-effect` (run the tests 10 times) ([CI run](https://github.com/vasilmkd/munit-cats-effect/actions/runs/1254950127), [commit](https://github.com/vasilmkd/munit-cats-effect/commit/8271306d00f8c6c5e75c764beebb38dbd537c213))
- [x] benchmarks (running overnight)

**Comment by vasilmkd** [comment]
Benchmark run:
```
Benchmark                                             (cpuTokens)   (size)   Mode  Cnt      Score      Error    Units
AsyncBenchmark.async                                          N/A      100  thrpt   20  17089.630 ±  233.423    ops/s
AsyncBenchmark.bracket                                        N/A      100  thrpt   20  12703.632 ±  125.217    ops/s
AsyncBenchmark.cancelable                                     N/A      100  thrpt   20  15965.453 ±  190.055    ops/s
AsyncBenchmark.race                                           N/A      100  thrpt   20   5168.704 ±   92.951    ops/s
AsyncBenchmark.racePair                                       N/A      100  thrpt   20  20953.263 ± 1293.916    ops/s
AsyncBenchmark.start                                          N/A      100  thrpt   20   5612.582 ±   51.983    ops/s
AsyncBenchmark.uncancelable                                   N/A      100  thrpt   20  24264.714 ±  444.949    ops/s
AttemptBenchmark.errorRaised                                  N/A    10000  thrpt   20   1183.276 ±   19.363    ops/s
AttemptBenchmark.happyPath                                    N/A    10000  thrpt   20   1597.755 ±   56.504    ops/s
BothBenchmark.happyPath                                       N/A    10000  thrpt   20     21.710 ±    2.025    ops/s
DeepBindBenchmark.async                                       N/A    10000  thrpt   20   1124.729 ±   59.706    ops/s
DeepBindBenchmark.delay                                       N/A    10000  thrpt   20   3210.739 ±  140.082    ops/s
DeepBindBenchmark.pure                                        N/A    10000  thrpt   20   3586.782 ±   92.121    ops/s
DispatcherBenchmark.scheduling                                N/A     1000  thrpt   20     55.520 ±    1.631  ops/min
HandleErrorBenchmark.errorRaised                              N/A    10000  thrpt   20   1326.647 ±   21.098    ops/s
HandleErrorBenchmark.happyPath                                N/A    10000  thrpt   20   1409.996 ±   24.353    ops/s
MapCallsBenchmark.batch120                                    N/A      N/A  thrpt   20    292.504 ±    4.402    ops/s
MapCallsBenchmark.batch30                                     N/A      N/A  thrpt   20     78.008 ±    1.747    ops/s
MapCallsBenchmark.one                                         N/A      N/A  thrpt   20      2.619 ±    0.058    ops/s
MapStreamBenchmark.batch120                                   N/A      N/A  thrpt   20   1749.884 ±   45.107    ops/s
MapStreamBenchmark.batch30                                    N/A      N/A  thrpt   20    671.870 ±   11.389    ops/s
MapStreamBenchmark.one                                        N/A      N/A  thrpt   20   1064.592 ±   18.450    ops/s
ParallelBenchmark.parTraverse                               10000     1000  thrpt   20    276.618 ±    5.185    ops/s
ParallelBenchmark.traverse                                  10000     1000  thrpt   20     33.295 ±    0.043    ops/s
RaceBenchmark.happyPath                                       N/A    10000  thrpt   20     20.491 ±    2.527    ops/s
RedeemBenchmark.errorRaised                                   N/A    10000  thrpt   20    781.779 ±   45.188    ops/s
RedeemBenchmark.happyPath                                     N/A    10000  thrpt   20    982.981 ±   64.599    ops/s
RedeemWithBenchmark.errorRaised                               N/A    10000  thrpt   20    958.634 ±   11.342    ops/s
RedeemWithBenchmark.happyPath                                 N/A    10000  thrpt   20   1351.870 ±   36.666    ops/s
RefBenchmark.getAndUpdate                                     N/A      N/A  thrpt   20   1939.302 ±   61.092    ops/s
RefBenchmark.modify                                           N/A      N/A  thrpt   20   1842.417 ±   54.113    ops/s
ShallowBindBenchmark.async                                    N/A    10000  thrpt   20    822.615 ±   13.842    ops/s
ShallowBindBenchmark.delay                                    N/A    10000  thrpt   20   3227.686 ±  203.463    ops/s
ShallowBindBenchmark.pure                                     N/A    10000  thrpt   20   3601.828 ±  127.129    ops/s
WorkStealingBenchmark.alloc                                   N/A  1000000  thrpt   20      6.617 ±    0.284  ops/min
WorkStealingBenchmark.manyThreadsSchedulingBenchmark          N/A  1000000  thrpt   20     14.180 ±    0.303  ops/min
WorkStealingBenchmark.runnableScheduling                      N/A  1000000  thrpt   20    112.354 ±    1.958  ops/min
WorkStealingBenchmark.scheduling                              N/A  1000000  thrpt   20     11.141 ±    2.610  ops/min
```

**Comment by vasilmkd** [comment]
Old results from the queue unification PR:
```
Benchmark                                             (cpuTokens)   (size)   Mode  Cnt      Score      Error    Units
AsyncBenchmark.async                                          N/A      100  thrpt   20  16463.158 ±  249.595    ops/s
AsyncBenchmark.bracket                                        N/A      100  thrpt   20  12412.039 ±  143.258    ops/s
AsyncBenchmark.cancelable                                     N/A      100  thrpt   20  15881.182 ±  224.176    ops/s
AsyncBenchmark.race                                           N/A      100  thrpt   20   5282.131 ±  240.079    ops/s
AsyncBenchmark.racePair                                       N/A      100  thrpt   20  19844.984 ± 1053.497    ops/s
AsyncBenchmark.start                                          N/A      100  thrpt   20   4899.008 ±  407.314    ops/s
AsyncBenchmark.uncancelable                                   N/A      100  thrpt   20  23979.278 ±  554.653    ops/s
AttemptBenchmark.errorRaised                                  N/A    10000  thrpt   20   1082.108 ±   13.725    ops/s
AttemptBenchmark.happyPath                                    N/A    10000  thrpt   20   1553.057 ±   32.347    ops/s
BothBenchmark.happyPath                                       N/A    10000  thrpt   20     22.079 ±    1.422    ops/s
DeepBindBenchmark.async                                       N/A    10000  thrpt   20   1089.312 ±   44.340    ops/s
DeepBindBenchmark.delay                                       N/A    10000  thrpt   20   3240.221 ±   91.184    ops/s
DeepBindBenchmark.pure                                        N/A    10000  thrpt   20   3650.951 ±   59.833    ops/s
DispatcherBenchmark.scheduling                                N/A     1000  thrpt   20     58.608 ±    3.046  ops/min
HandleErrorBenchmark.errorRaised                              N/A    10000  thrpt   20   1310.049 ±   19.005    ops/s
HandleErrorBenchmark.happyPath                                N/A    10000  thrpt   20   1397.669 ±   19.320    ops/s
MapCallsBenchmark.batch120                                    N/A      N/A  thrpt   20    279.739 ±    5.304    ops/s
MapCallsBenchmark.batch30                                     N/A      N/A  thrpt   20     78.485 ±    2.171    ops/s
MapCallsBenchmark.one                                         N/A      N/A  thrpt   20      2.761 ±    0.114    ops/s
MapStreamBenchmark.batch120                                   N/A      N/A  thrpt   20   1640.282 ±   45.051    ops/s
MapStreamBenchmark.batch30                                    N/A      N/A  thrpt   20    681.799 ±    7.647    ops/s
MapStreamBenchmark.one                                        N/A      N/A  thrpt   20   1079.243 ±   21.200    ops/s
ParallelBenchmark.parTraverse                               10000     1000  thrpt   20    271.972 ±    7.064    ops/s
ParallelBenchmark.traverse                                  10000     1000  thrpt   20     33.353 ±    0.044    ops/s
RaceBenchmark.happyPath                                       N/A    10000  thrpt   20     22.783 ±    1.568    ops/s
RedeemBenchmark.errorRaised                                   N/A    10000  thrpt   20    773.892 ±   18.937    ops/s
RedeemBenchmark.happyPath                                     N/A    10000  thrpt   20    981.409 ±   74.080    ops/s
RedeemWithBenchmark.errorRaised                               N/A    10000  thrpt   20   1012.925 ±   18.995    ops/s
RedeemWithBenchmark.happyPath                                 N/A    10000  thrpt   20   1359.581 ±   37.402    ops/s
RefBenchmark.getAndUpdate                                     N/A      N/A  thrpt   20   1939.056 ±   70.017    ops/s
RefBenchmark.modify                                           N/A      N/A  thrpt   20   1803.804 ±   49.859    ops/s
ShallowBindBenchmark.async                                    N/A    10000  thrpt   20    845.795 ±    7.458    ops/s
ShallowBindBenchmark.delay                                    N/A    10000  thrpt   20   3286.053 ±   92.127    ops/s
ShallowBindBenchmark.pure                                     N/A    10000  thrpt   20   3773.739 ±  157.648    ops/s
WorkStealingBenchmark.alloc                           1000000  thrpt   20    6.306 ± 0.182  ops/min
WorkStealingBenchmark.manyThreadsSchedulingBenchmark  1000000  thrpt   20   13.094 ± 0.297  ops/min
WorkStealingBenchmark.runnableScheduling              1000000  thrpt   20  114.017 ± 4.936  ops/min
WorkStealingBenchmark.scheduling                      1000000  thrpt   20   11.420 ± 2.104  ops/min
```

**Comment by vasilmkd** [comment]
Benchmark results look stable, which is to be expected. This PR makes changes to the blocking code path of the runtime, with the only change in the hotter path being to the code which wakes up other worker threads, which in itself is an expensive volatile operation and the JVM seems to be able to elide the newly added volatile read successfully.

**Comment by vasilmkd** [comment]
Local benchmarks

`series/3.x`:
```
Benchmark                          (size)   Mode  Cnt   Score   Error    Units
WorkStealingBenchmark.alloc       1000000  thrpt   20   3.765 ± 0.029  ops/min
WorkStealingBenchmark.scheduling  1000000  thrpt   20  12.606 ± 0.500  ops/min
```

`This PR`:
```
Benchmark                          (size)   Mode  Cnt   Score   Error    Units
WorkStealingBenchmark.alloc       1000000  thrpt   20   3.780 ± 0.046  ops/min
WorkStealingBenchmark.scheduling  1000000  thrpt   20  12.549 ± 0.507  ops/min
```

**Comment by vasilmkd** [comment]
~~It may be worth targeting this PR at `series/3.2.x` in light of https://github.com/typelevel/fs2/issues/2628 and I would follow it up with an optimization that spawns fewer threads. I can do it pretty easily after this PR.~~

~~All of this would be released in a potential `3.2.10`.~~

~~@djspiewak~~

Edit: This comment is largely irrelevant because the immediate issue has been resolved in fs2.

**Review by djspiewak — DISMISSED** [review]

**Review by djspiewak — DISMISSED** [review]

**Comment by vasilmkd** [comment]
Rebased on the latest changes to `series/3.x`.

**Review by djspiewak — APPROVED** [review]

**Pull request merged**
