### PR TITLE
add unsafe constructors to MVar and Semaphore

### PR DESCRIPTION
**Pull request by Odomontois**

### CODE REVIEW

**Comment by ChristopherDavenport** [comment]
I don't follow why this is necessary rather than calling `unsafeRunSync` directly. These variants break referential transparency, so I personally would prefer if we didn't make it easy as it will lead to bugs.

**Comment by Odomontois** [comment]
If we have only `[F[_] : Concurrent]` in the context, we have nothing like the `unsafeRunAsync` 
This is following to #373 
@alexandru said he is personally against two-effect constructors, so I consider this as a direct veto.
While having `[Init[_]: Sync, F[_]: Concurrent]` I can at least to `Init.delay(unsafe)` in my internal util library as a substition.
Right now I have cenobite-level ugly code, trying to unprivate (Async|Concurrent)(MVar|Semaphore)

**Comment by SystemFw** [comment]
@Odomontois running things unsafely requires you to have a `ConcurrentEffect` constraint, from where you can `toIO.unsafeRunSync`. I don't see why this case needs an exception (ideally we should remove the `unsafe` constructor for `Ref` as well).

**Comment by mpilquist** [comment]
FWIW, I'm in support of #373 or otherwise exposing unsafe constructors (https://github.com/typelevel/cats-effect/issues/373#issuecomment-428348952)

**Comment by SystemFw** [comment]
ah,  `mapK` doesn't work then

**Comment by Odomontois** [comment]
@SystemFw As I mentioned in the issue, a lot of projects in our company uses variant of `ReaderT[Task, ApplicationContext, ?]` as `F[_]`. So we can't require `Effect` or it's subclasses

**Comment by SystemFw** [comment]
@Odomontois yeah sorry, I didn't immediately link the motivation for this issue to #373

**Comment by Odomontois** [comment]
The only not-super-ugly solution I'm  came up with is the two parameter classes like
```
trait CreateMVar[I[_], F[_]]{
      def of[A](a: A) : I[MVar[F, A]]
      def empty[A] : I[MVar[F, A]]
}
```
This is the current internal solution, but I've thought it may be a common problem, since community is moving towards tagless finalish designs.

**Comment by SystemFw** [comment]
A similar problem prompted us to redesign http4s. I one hundred percent agree it's worth solving. I'm just unsure which one is the best way.  Maybe the dual constructor in #373 is, and we should move this discussion back there.

**Comment by ChristopherDavenport** [comment]
I would suggest that we move to solve the two separate effect constructors, rather than exposing unsafe systems into  our API within the capabilities of the typeclasses.

**Comment by Odomontois** [comment]
> I would suggest that we move to solve the two separate effect constructors, rather than exposing unsafe systems into our API within the capabilities of the typeclasses.

Does that mean, that existing unsafe constructors in `Ref` and `Deferred` will be deprecated?

**Comment by ChristopherDavenport** [comment]
I personally think that they should be.

**Comment by mpilquist** [comment]
If we have the dual type constructor approach, folks that are sure they need unsafe creation can always use `SyncIO` for the construction effect followed by `unsafeRunSync`. This is nice b/c it reduces our `unsafe` surface area through orthogonal APIs.

**Comment by djspiewak** [comment]
This concerns me a lot. If you don't have an `Effect` constraint because you're in some complex polymorphic context (e.g. `Kleisli`), then *all the more* reason to not do something unsafe like the proposed constructors. Why not just `liftM`? Messing up effect sequencing *always* bites you in the end.

I guess I'm just really unclear on why this is *necessary*. I understand why it's convenient. And I also want to make it really clear why it's *dangerous*. Especially in library code like http4s.

**Comment by SystemFw** [comment]
>  And I also want to make it really clear why it's dangerous. Especially in library code like http4s.

Sorry, I gave you the impression (I think) that we're using unsafe constructs in http4s. We're not.

I just meant to say that we added a type param so that the effect you do your `Request` is not necessarily the same the Stream body response is in. So basically you could have an OptionT[F, ?] of Response whose body is `Stream[F` (as opposed to `Stream[OptionT[F,`).

**Comment by djspiewak** [comment]
> I just meant to say that we added a type param so that the effect you do your Request is not necessarily the same the Stream body response is in

Ah yeah that makes total sense. We've done a lot of that sort of thing in quasar. Why would that make it desirable to have unsafe constructors though?

**Comment by SystemFw** [comment]
> Why would that make it desirable to have unsafe constructors though?

I meant that if we don't add unsafe constructors to things in cats-effect, _and_ we don't add dual constructors to them, then you have to `liftF` all over the place (which I'm not even saying is undesirable, just making clear that it's the case)

**Comment by SystemFw** [comment]
But generally speaking I don't like `unsafe` versions of things :)

**Comment by mpilquist** [comment]
And the `liftF` approach doesn't help in Scala.js, where you might *need* synchronous unsafe construction b/c the UI framework is not effect aware.

**Comment by djspiewak** [comment]
> then you have to liftF all over the place (which I'm not even saying is undesirable, just making clear that it's the case)

Is this the case if you use cats-mtl? Generally I spend very little time `liftF`ing these days unless it's for a locally-scoped explicit monad transformer.

**Comment by SystemFw** [comment]
> Huge 👍 for the mapK approach.

I agree, but @mpilquist has a case in scala.js where it didn't work from him. He can explain better :)

**Comment by ChristopherDavenport** [comment]
The problem with mapK I see is that creation can be done Synchronous, but creation of the value requires a Concurrent/Async constraint. So if you wanted to create in SyncIO and then translate to IO you could not.

**Comment by djspiewak** [comment]
@ChristopherDavenport Why is it not possible to define `SyncIO ~> IO`?

**Comment by ChristopherDavenport** [comment]
It is but you cant create an MVar/Ref/etc with only a `Sync` you need `Concurrent/Async` currently.

**Comment by SystemFw** [comment]
You can create a `Ref` with a `Sync`.
You need `Concurrent` for `Deferred` and `MVar`.

**Comment by djspiewak** [comment]
Leaving aside `Concurrent` for the moment… What feasible transformer stacks have a `Sync` but not an `Async`?

**Comment by mpilquist** [comment]
The `mapK` solution doesn't work for me but I agree it's a far superior solution when it does work.

I need either unsafe construction (gross) or the ability to create a `Ref[F, X]` for `F[_]: Concurrent` in a *synchronous* effect type. My use case is in Scala.js using scalajs-react, where I need to initialize a `Ref[F, X]` at component instantiation time b/c I'm using it for storing some component state. Scalajs-react is effect aware but only for synchronous effect types (e.g., `SyncIO` or `scalaz.effect.IO`). Scalajs-react uses a type `CallbackTo[A]` and we can provide a `SyncIO ~> CallbackTo` instance but we cannot provide `IO ~> CallbackTo` as the latter doesn't have any support for async constructors.

Hence, the best I can do now is use `CallbackTo.lift(() => Ref.of[IO, X](...).unsafeRunSync)`.

**Comment by djspiewak** [comment]
So I'll admit I'm really playing catch-up here, and I'm massively grateful for all your patience…

It sounds like we can conceptually *construct* an `MVar`/`Semaphore` without an `Async` (so long as we have a `Sync`), but we can't *use* it without one. Is that accurate? Without looking at the implementation, I'm guessing this isn't something we can resolve simply by removing constraints from the constructor and adding them to usage methods?

**Comment by mpilquist** [comment]
No worries. We *could* do that (and the original PR had the constraints on the individual methods even). We changed it though b/c we support both an `Async[F]` and `Concurrent[F]` backed instance for `Ref`, `Semaphore`, and some other types.

**Comment by djspiewak** [comment]
Oh is this one of those situations where we conceptually wanted something like `implicit F: EitherK[Async, Concurrent, F]`, but instead it was split into two separate constructors?

**Comment by SystemFw** [comment]
tbh, I'm not sure the `Async` versions are very useful. 
Definitely not `Deferred` (without concurrency it's just a `val`). 
`Async` means uninterruptible, but I guess that could be achieved differently.

**Comment by mpilquist** [comment]
Not necessarily, because you might want a `Ref[IO, X]` using `Async[IO]` -- to "disable" cancelation. I agree with Fabio though -- I'm not sure the `Async` versions justify their cost.

**Comment by SystemFw** [comment]
> to "disable" cancelation

How about  a version with `Concurrent` that wrapped all methods with `uninterruptible`, for that use case?

**Comment by djspiewak** [comment]
I guess my general feeling on this is that the constructors are over-constrained. If it's *conceptually* valid to take a non-effect-wrapped version of the constructor and then wrap it in an arbitrary `Sync`, and there are real use-cases which are dependent on that, then we should be able to write the types and implementation in support of that concept. The fact that we can't right now feels like something is wrong, either in the constructors or in the implementations. I realize it's a bit more complicated than that due to the nature of concurrent evaluation, but that's my general thought.

**Comment by SystemFw** [comment]
@djspiewak you might as well be right.
The downside is the usual though: adding a constraint to the methods makes _usage_ be overconstrained. For some types it won't matter (`Deferred` usage needs `Concurrent`), for others it might.

**Comment by ChristopherDavenport** [comment]
def createMVar[F[_]: Sync, G[_]: Concurrent]: F[MVar[G]]` seems to make sense to me for that scope.

**Comment by mpilquist** [comment]
If we're talking about a cats-effect 2.0 change here, I'd be all for getting rid of the uninterruptible variants entirely. Note this change has to percolate through all the concurrent types -- e.g. we have to be able to construct a `Deferred[F, A]` for a `F[_]: Sync` in order to be able to construct a `Ref[F, A]` for a `F[_]: Sync`.

However, I'm also interested in a solution for cats-effect 1.x and it seems like `mapK` and a dual type constructor creator would accomplish that.

**Comment by djspiewak** [comment]
@alexandru How do you feel about adding the dual type constructor variants of the constructors *along side* the current single type constructor versions? I agree the dual variant is really syntactically annoying, I just wonder if there's any other way of doing it without being actively unsafe (such as this PR).

**Comment by alexandru** [comment]
If we added the two-effect constructors, which are already on `master`, is this issue still relevant?

**Comment by djspiewak** [comment]
If the dual effect constructors and mapK are present in master, then it doesn’t feel like this issue is relevant anymore. That’s just my thought though.

**Comment by mpilquist** [comment]
I agree. Folks can always use SyncIO + dual constructor + unsafeRunSync.

**Comment by alexandru** [comment]
👍 cool, then I'm closing this one for now

**Pull request closed without merging**
