### PR TITLE
Remove `-Xcheckinit` compiler flag

### PR DESCRIPTION
**Pull request by armanbilge**
I'm pretty sure this is responsible for those auto-generated volatile fields that have been taunting @vasilmkd 😆

### CODE REVIEW

**Comment by vasilmkd** [comment]
I'm in favor of removing this, because it causes a volatile field `bitmap$init` to be created on a lot of classes. This slows down constructors and field accesses (which we work hard to avoid), but the constructors remain. Examples:
https://github.com/typelevel/cats-effect/pull/2534#discussion_r748775008 and https://github.com/typelevel/cats-effect/pull/2473.

**Comment by armanbilge** [comment]
I don't know how hard it would be to setup, but if this check is important, maybe we can enable this flag only for testing/CI but remove for release?

**Comment by vasilmkd** [comment]
No, I don't agree with that. That could hide bugs. Either there is a good reason that this flag was included and @djspiewak can shed some light on it, or I really don't know why this is here and we can remove it everywhere.

**Comment by armanbilge** [comment]
Btw it was introduced here:
https://github.com/typelevel/cats-effect/pull/874/commits/de1f68bb4fff5f4fbbf3432069258e96609d02b5#diff-928a6eabff1094f1b64a2d1b6bc7574c5a483476ec3fee98c16d1fe46aae9d0d

**Comment by vasilmkd** [comment]
Before:
```
[info] Benchmark             (size)   Mode  Cnt      Score     Error  Units
[info] AsyncBenchmark.start     100  thrpt    5  12890.043 ± 107.889  ops/s
```

After:
```
[info] Benchmark             (size)   Mode  Cnt      Score     Error  Units
[info] AsyncBenchmark.start     100  thrpt    5  15683.946 ± 296.763  ops/s
```

**Review by djspiewak — APPROVED** [review]
Sincerely no idea why I explicitly added this. So odd.

**Comment by armanbilge** [comment]
@vasilmkd should we consider reverting some of the changes you made to workaround this? E.g. moving things into constructors. Or maybe those were good ideas anyway 👍

**Pull request merged**
