### PR TITLE
Third Party Resource Links

### PR DESCRIPTION
**Pull request by daniel-ciocirlan**
cc @djspiewak 

Added learning links by third party resources in the documentation website.

For context: I run this website called [Rock the JVM](https://rockthejvm.com/) which creates free and paid learning material on all major tools in the Scala ecosystem. This Cats Effect course has been live since August 2021 with overwhelmingly positive feedback. I think the course would benefit many more people if only they knew it existed, hence this PR.

The PR also includes learning resources from other creators I'm aware of, plus some selected YouTube videos and blog posts. Please let me know in the comments if you have suggestions on what else to include, and I'll add them to the PR.

### CODE REVIEW

**Review by vasilmkd — APPROVED** [review]
Keep rocking the JVM @daniel-ciocirlan! Love your content.

**Comment by daniel-ciocirlan** [comment]
The build failure seems unrelated - flaky?

**Comment by samspills** [comment]
Agreed that the build failure looks flaky. I'm going to close and reopen the PR to kick it off fresh

**Review by samspills — APPROVED** [review]
Nice!! I ran locally and styling looked good and the links all worked (and also all look very useful of course)

<details><summary>screenshot for posterity :D </summary>

image

</details>

**Pull request merged**
