### PR TITLE
Nix shell -> Nix flake

### PR DESCRIPTION
**Pull request by rossabaker**
Everything else in the Typelevel org is a flake these days.  This gets things refreshed so the scala-native toolchain is available.

### CODE REVIEW

**Comment by rossabaker** [comment]
flake.lock should be updated after https://github.com/typelevel/typelevel-nix/pull/90 merges.

**Comment by rossabaker** [comment]
Canceled the CI pending the flake update to save some compute.

**Comment by djspiewak** [comment]
Out of curiosity, what happens to those of us who are using `direnv` but *not* using Nix?

**Comment by rossabaker** [comment]
I have wondered about that, but never seen an existence proof of such people.  I'm content to leave it out, but most Nix users will end up adding it locally, and no non-Nix user has ever complained about it.

(I would be highly interested in a global direnv setting that said "if there's no .envrc but there's a flake, use that", but that's not to be solved here...)

**Comment by djspiewak** [comment]
```
direnv: using nix
environment:516: nix-shell: command not found
```

Apparently you just get this persistent error. Or you can block the `.envrc`, which appears to be what I was doing on http4s before I ran this experiment.

**Comment by rossabaker** [comment]
I won't fight removing the .envrc.  A tiny handful of Nix users will find it handy, and a tinier handful of Nixless Direnv users will want to keep it blocked.  I'd find it much more compelling to remove it if anyone were creating a _different_ .envrc.  Otherwise, it's blocked by default, and what I believe to be the vast majority of direnv users will get a useful definition when they unblock it.

**Comment by djspiewak** [comment]
Yeah I think it's fine since I don't have any compelling need for direnv in CE specifically. I won't deny you the convenience that I'm not using.

**Review by djspiewak — APPROVED** [review]

**Pull request merged**
