### PR TITLE
WIP on microsite w/ tut doc

### PR DESCRIPTION
**Pull request by tpolecat**
This adds a microsite with tut doc. Need to:

- [ ] Add some tut doc for basic usage.
- [ ] Move some of the deeper stuff in the README into the doc.
- [ ] Maybe add the "why no `both`" text in there as well.
- [ ] Synchronize the residual README and microsite index.
- [ ] Pick a new and more delightful color palette maybe.
- [ ] Etc.

👎  for now, work in progress

### CODE REVIEW

**Comment by tpolecat** [comment]
Let me know if the plan above displeases you.

**Comment by djspiewak** [comment]
In this, I am well pleased.

Though the pedant in me would rather we use `doc/` rather than `docs/` (e.g. it's `src/test/` not `src/tests/`, and of course `src/` is pronounced "source" not "sources").

**Comment by tpolecat** [comment]
Yeah, it's `docs` because there's a built-in sbt task called `doc` and things get confusing because you have two scopes with the same name.

**Comment by djspiewak** [comment]
😱😵💀

**Comment by alexandru** [comment]
Any progress or thoughts on this?

**Comment by tpolecat** [comment]
No, I haven't had a chance to look back at it. I'll close and someone else can pick it up maybe.

**Pull request closed without merging**
