### PR TITLE
`SyncIO#>>` parameter should be by-name

### PR DESCRIPTION
**Pull request by vasilmkd**
Unfortunately, this is a binary incompatible change...

### CODE REVIEW

**Comment by djspiewak** [comment]
Ahhhh this is a concerning oversight. We should be able to avoid the binary breakage by overloading though. If we define a `private[effect] def >>(...)` eager version alongside the lazy version, it should satisfying the old binary linkage without polluting the public API.

**Comment by djspiewak** [comment]
Ahhhh this is a concerning oversight. We should be able to avoid the binary breakage by overloading though. If we define a `private[effect] def >>(...)` eager version alongside the lazy version, it should satisfying the old binary linkage without polluting the public API.

**Comment by vasilmkd** [comment]
That's very smart. Recompiled code against the next version will pick up the new signature, right?

**Comment by djspiewak** [comment]
> That's very smart. Recompiled code against the next version will pick up the new signature, right?

Yep! It would only be old previously-linked code. This is kind of a general technique: when you want to break something, hide the old thing as package-private and, due to the granularity of Scala's access modifiers, you're basically getting the same ABI while still hiding the replaced entity from source resolution.

**Comment by vasilmkd** [comment]
Awesome, thank you! I will push out the change shortly.

**Review by djspiewak — APPROVED** [review]

**Review by rossabaker — APPROVED** [review]

**Pull request merged**
