### PR TITLE
Address issues with the blocking mechanism of the thread pool

### PR DESCRIPTION
**Pull request by vasilmkd**
Addresses issues identified in #2304.

### CODE REVIEW

**Comment by vasilmkd** [comment]
Next step, publishing locally and testing against the `fs2` test suite.

**Comment by vasilmkd** [comment]
After running the `fs2` test suite for more than 10 times in a row, everything is fine. Continuing with publishing a snapshot release.

**Comment by vasilmkd** [comment]
```scala
"io.vasilev" %%% "cats-effect" % "3.2-23-cc99a6c"
```
is currently propagating.

**Comment by vasilmkd** [comment]
Running the CI of my copy of the original `munit-cats-effect` issue repeatedly seems to be working fine.
https://github.com/vasilmkd/munit-cats-effect/actions/runs/1209650570

**Comment by vasilmkd** [comment]
The snapshot release is also used in the original issue: https://github.com/typelevel/munit-cats-effect/pull/124. Working fine.

**Comment by vasilmkd** [comment]
Running the `BlockingStressSpec` with 10000 fibers which all execute blocking actions (which depending on interleaving can result in up to 10000 helper threads being spawned) works on the Cats Effect thread pool without issues.

Changing the test runtime from the CE thread pool to `scala.concurrent.ExecutionContext.global` and running the same experiment bogs down and potentially ends in a deadlock.

Feel free to try it yourself.

**Comment by vasilmkd** [comment]
A thread snapshot after running the 10000 helper thread test:
Screen Shot 2021-09-07 at 16 48 02

There are no `-blocking-helper-$index` threads visible, which means that they all finished running and died out as soon as the blocking actions were completed.

**Review by djspiewak — APPROVED** [review]

**Pull request merged**
