### PR TITLE
Fix non-determinism in MVarSpec tests

### LINKED ISSUE #1015: New Nondeterminism in MVarSpec
```
[info] MVarSpec
[error] x put is cancelable
[error]  Set(1, 2) != Set(1, 3) (MVarSpec.scala:49)
[error] Added (1)
[error] 2
[error] 
[error] Missing (1)
[error] 3
[error] 
[info] + take is cancelable
```

### PR DESCRIPTION
**Pull request by vasilmkd**
Resolves #1015.

### CODE REVIEW

**Comment by djspiewak** [comment]
This is very clever! There's still a *tiny* window of nondeterminism though, and I'm not sure if it's worth trying to close it. Basically, `poll` will turn into an `IO.Unmask`, which will interpret to its body (in this case, the `mvar.put`), but *before* the `mvar.put` is hit, it will first check `canceled`. So it's actually still possible that the `put` will never run.

**Comment by vasilmkd** [comment]
Is that even realistically possible to close?

**Comment by djspiewak** [comment]
Holy crap we hit #1019 again…

**Comment by djspiewak** [comment]
Hmm, I saw this failure after restart:

```
 [error] ! modify is cancelable on f
[error]  java.util.concurrent.TimeoutException: null (Runners.scala:187)
[error] cats.effect.Runners.$anonfun$1(Runners.scala:187)
[info] Total for specification MVarSpec
```

**Comment by vasilmkd** [comment]
Oops.

**Comment by vasilmkd** [comment]
Rebased with the new changes.

**Comment by vasilmkd** [comment]
All green. I fixed the `modify is cancelable on f` hanging test.

**Pull request merged**
