### PR TITLE
Scala 2.13.2

### PR DESCRIPTION
**Pull request by joroKr21**

### CODE REVIEW

**Comment by rossabaker** [comment]
Does metals work on 2.13.2 yet? I usually hold off on Scala bumps for that.

**Comment by rossabaker** [comment]
Though I don't think it's the default (not near computer to check), so it probably doesn't matter much.

**Comment by alexandru** [comment]
@rossabaker sorry, I thought it isn't a problematic change, seeing the tests pass.

I'm not using Metals, IDK.

If you want we can revert the change.

**Comment by alexandru** [comment]
@rossabaker btw, this particular change is only related to what Travis uses, doesn't affect local dev.

**Comment by rossabaker** [comment]
Nope, I withdraw my concern.  I've been burned on other projects by merging Scala bumps too quickly because Metals takes a few days to catch up, but you're right about it being CI-only.

**Pull request merged**
