### PR TITLE
Cattify cats-effect perks

### PR DESCRIPTION
**Pull request by Zelenya**

### CODE REVIEW

**Review by vasilmkd — APPROVED** [review]
This is oh so cool. Thank you!

**Comment by djspiewak** [comment]
This looks super awesome! I think we might need to make the images a bit less padded though. Here's what it currently renders like:

**Comment by Zelenya** [comment]
Recropped

**Comment by vasilmkd** [comment]
I'll grab a screenshot.

**Comment by vasilmkd** [comment]
I think the images are now good, but our text seems to be a bit off. Can we do some CSS magic here?
Screen Shot 2021-06-07 at 09 37 36

**Comment by djspiewak** [comment]
Actually I think that's what it's supposed to look like. Or at the very least, I think it looks pretty solid :-)

**Pull request merged**
