### PR TITLE
cats-1.0.0

### PR DESCRIPTION
**Pull request by rossabaker**

### CODE REVIEW

**Comment by rossabaker** [comment]
I propose that this be released as 0.6.1.  The only change is a fully compatible version of cats, to get rid of irritating eviction warnings.

**Comment by alexandru** [comment]
I would go with 0.7, since we aren’t doing semver, but I don’t care much.

**Comment by tpolecat** [comment]
Are we waiting for anything else? I'm fine with either version number.

**Comment by rossabaker** [comment]
Just needs a release, which I believe only @djspiewak can do.

**Comment by djspiewak** [comment]
@rossabaker Actually, anyone with Sonatype permissions to the `org.typelevel` groupId can push a cats-effect release.  For the record, steps:

```bash
$ VERSION=v1.0
$ git tag -s -m "Tagging $VERSION" $VERSION
$ sbt clean release
$ git push upstream $VERSION
```

Probably worth throwing a `+test` in there before `release`, just out of paranoia.  But it's more or less the same idea, and technically `+test` doesn't work right now because of SBT 1.0 shenanigans.

I personally vote for the new release to be 1.0, reflecting a commitment to full-released stability, but given that the core has been rewritten quite recently, that might not necessarily be the best move.  I'm open to either approach.  0.6.1 would technically be appropriate from a strictly semver standpoint.

**Comment by rossabaker** [comment]
I'm :-1: on 1.0 with so many breaking and unresolved issues on the board.  #67, #73, #88, #93, and #104 in particular.  Those are all going to require a major bump if acted upon.

In the release instructions above, make sure it's `push --tags`.  We didn't get a tag on 0.6.  I don't have org.typelevel Sonatype access.

**Comment by djspiewak** [comment]
> I'm 👎 on 1.0 with so many breaking and unresolved issues on the board.

Fair.

> In the release instructions above, make sure it's push --tags. We didn't get a tag on 0.6.

Oh lol my bad.  Fixed.

**Pull request merged**
