### PR TITLE
Actually restore `IODeferred` specialization

### PR DESCRIPTION
**Pull request by armanbilge**

### CODE REVIEW

**Comment by armanbilge** [comment]
Well this is very embarrassing 😳 I don't think we ever actually brought it back in https://github.com/typelevel/cats-effect/pull/3403. That also probably means the benchmarks I offered there are completely moot 🤔

**Comment by armanbilge** [comment]
Oh gosh! That probably explains why this PR didn't improve benchmarks either 😭 
- https://github.com/typelevel/cats-effect/pull/3435

**Comment by armanbilge** [comment]
#### This PR

```
Benchmark                   (count)   Mode  Cnt     Score    Error  Units
DeferredBenchmark.cancel         10  thrpt   20    41.553 ±  0.708  ops/s
DeferredBenchmark.cancel        100  thrpt   20     4.882 ±  0.291  ops/s
DeferredBenchmark.cancel       1000  thrpt   20     0.413 ±  0.014  ops/s
DeferredBenchmark.complete       10  thrpt   20    31.238 ±  3.586  ops/s
DeferredBenchmark.complete      100  thrpt   20     8.244 ±  1.767  ops/s
DeferredBenchmark.complete     1000  thrpt   20     0.993 ±  0.364  ops/s
DeferredBenchmark.get            10  thrpt   20  1650.125 ± 54.401  ops/s
DeferredBenchmark.get           100  thrpt   20   256.456 ±  2.135  ops/s
DeferredBenchmark.get          1000  thrpt   20    26.779 ±  0.231  ops/s
```

#### series/3.4.x

```
Benchmark                   (count)   Mode  Cnt     Score    Error  Units
DeferredBenchmark.cancel         10  thrpt   20    40.660 ±  0.732  ops/s
DeferredBenchmark.cancel        100  thrpt   20     4.272 ±  0.124  ops/s
DeferredBenchmark.cancel       1000  thrpt   20     0.355 ±  0.017  ops/s
DeferredBenchmark.complete       10  thrpt   20    30.792 ±  3.347  ops/s
DeferredBenchmark.complete      100  thrpt   20     8.399 ±  1.543  ops/s
DeferredBenchmark.complete     1000  thrpt   20     1.186 ±  0.261  ops/s
DeferredBenchmark.get            10  thrpt   20  1021.676 ± 12.172  ops/s
DeferredBenchmark.get           100  thrpt   20   165.704 ±  4.359  ops/s
DeferredBenchmark.get          1000  thrpt   20    18.971 ±  1.378  ops/s
```

**Review by djspiewak — APPROVED** [review]
Lol that's an embarrassing miss. I completely failed to catch it during the review, sorry.

**Pull request merged**
