### PR TITLE
add clock extension method for creating java.time.Instant

### PR DESCRIPTION
**Pull request by jbwheatley**
I mainly end up converting clock's realTime to `Instant` and so define this extension method in my projects, so thought it might be useful to add it here if other people deal with `Instant` a lot

### CODE REVIEW

**Comment by djspiewak** [comment]
I quite like this, but there's a little bit of a problem, which is that ScalaJS doesn't have `java.time` at all. So if anyone *calls* this function in cross-compiled code, not realizing the problems with it, the resulting JS sources will simply not link. In theory this might show up in their build though, so perhaps that isn't a problem.

Anyone else have strong opinions on this? I'm moderately 👍

**Comment by vasilmkd** [comment]
Can it be jvm specific?

**Comment by djspiewak** [comment]
> Can it be jvm specific?

It could be if we added a `ClockPlatform` trait. I'm usually a little reticent to do stuff like that, though CE3 does a fair amount of it, so… *shrug* :-) I would accept that.

**Comment by jbwheatley** [comment]
Cool, I can add the `ClockPlatform` trait 👍

**Review by djspiewak — APPROVED** [review]
I quite like this. I'm going to leave it open for comments for a longer just to see what people say. Thank you!

**Comment by bplommer** [comment]
I like this. Always wanted it but assumed it was decided not to add it because `Instant` is jvm-only.

**Pull request merged**
