### PR TITLE
Add SemigroupK instance for IO

### LINKED ISSUE #94: SemigroupK[IO]
I was writing a DSL that required boolean OR logic with early exit and used `SemigroupK` as a way to achieve this, however without an instance I was not able to use `IO`. It would be good to provide one.

### PR DESCRIPTION
**Pull request by LukaJCB**
Should fix #94

### CODE REVIEW

**Comment by LukaJCB** [comment]
Mima rightfully complains about binary incompatability, should I add an exception in the build.sbt?

**Comment by alexandru** [comment]
Adding an exception is OK, since that's a `private[effect]` trait.

We should probably change `trait IOInstances` to `abstract class IOInstances` too. Better for binary compatibility and there's no reason for working with a `trait` here, especially since this stuff is private.

**Comment by LukaJCB** [comment]
Yeah agreed! You want me to update that in this PR, or create another one? :)

**Comment by alexandru** [comment]
@LukaJCB can you fix this PR?

**Comment by LukaJCB** [comment]
@Alexandru can you restart the Travis build, it should work with the abstract class fix, no?

**Pull request merged**
