### PR TITLE
Reinlined travis build process

### PR DESCRIPTION
**Pull request by djspiewak**
My rule of thumb is this: are these scripts useful *outside* of the CI server?  The answer here is clearly no, and so they should be inlined into the `.travis.yml`.  I also played around with trying to get `coverage` to be a part of `ci`, but ran into an issue where I couldn't emulate dynamic key binding in SBT.

### CODE REVIEW

**Comment by djspiewak** [comment]
Don't merge. There's a problem with the `matrix`.

**Comment by djspiewak** [comment]
Merging this, since it's just infrastructural cleanup.

**Comment by alexandru** [comment]
@djspiewak inlining those scripts is totally fine, but now there's something wrong with the coverage

**Comment by djspiewak** [comment]
Yeah I see that.  I'll fix it.

**Pull request merged**
