### PR TITLE
Extra-concise version of `IOApp.Simple`

### PR DESCRIPTION
**Pull request by bplommer**
I'm really on the fence about whether this is a good idea or just me being phenomenally lazy, so curious what others think 🤷

### CODE REVIEW

**Comment by djspiewak** [comment]
Lmao. Let's let people bikeshed this a bit.

**Comment by armanbilge** [comment]
What I said on Discord is we could really benefit from a way to integrate with Scala 3 `@main` annotation.

**Comment by djspiewak** [comment]
> What I said on Discord is we could really benefit from a way to integrate with Scala 3 @main annotation.

Yeah that would be a huge win, but I think it's not configurable right now.

**Comment by mpilquist** [comment]
`@main` support would be nice. I don't like having too many ways of doing the same thing though and I'm also a bit concerned about moving the creation of the main `IO` in to a constructor call. Reminiscent of `App`.

**Comment by bplommer** [comment]
> What I said on Discord is we could really benefit from a way to integrate with Scala 3 `@main` annotation.

I think it would be reasonably simple to add syntax for something like `@main def run(arg1: Foo, arg2: Bar) = myIO(arg1, arg2).unsafeRunIOApp` that desugars to something like
```scala
@main def run(arg1: Foo, arg2: Bar) = new IOApp.Simple {
  override val run: IO[Unit] = myIO(arg1, arg2)
}.main(Array.empty)
```

**Comment by armanbilge** [comment]
Scala 3.2.0 now offers https://scala-lang.org/api/3.x/scala/annotation/MainAnnotation.html#

**Pull request closed without merging**
