### PR TITLE
Fix duplicated IORuntime config docs -> series/3.3.x

### PR DESCRIPTION
**Pull request by armanbilge**
It's literally the same commits as https://github.com/typelevel/cats-effect/pull/2883, since the PR was based on 3.3.x. Just merged to the wrong place, my bad.

### CODE REVIEW

**Review by djspiewak — APPROVED** [review]

**Comment by djspiewak** [comment]
Oh this is gonna be good fun when we backport merge the branches together…

**Comment by armanbilge** [comment]
Why's that? Since it's the same commits it won't be any issue.

**Comment by djspiewak** [comment]
> Why's that? Since it's the same commits it won't be any issue

Oh is it literally the same commits and not a rebase? Then it should be fine.

**Comment by armanbilge** [comment]
Yeah it was honestly a very stupid mistake :)

**Pull request merged**
