### PR TITLE
Always enhance caught `Throwable`s

### PR DESCRIPTION
**Pull request by vasilmkd**
This should match the behavior of Cats Effect 2.

### CODE REVIEW

**Comment by vasilmkd** [comment]
I specifically pushed 2 commits, one augments `NonFatal` `Throwable`s and the other fatal errors. Let me know if I should revert the fatal error case. I know we're not supposed to allocate objects in that case, but I await further instructions.

**Comment by vasilmkd** [comment]
This is not as straightforward as it appears.

**Comment by vasilmkd** [comment]
Or maybe it is.

**Comment by vasilmkd** [comment]
Code:
```scala
import cats.data._
import cats.effect._
import cats.syntax.all._

object Main extends IOApp.Simple {
  def run: IO[Unit] =
    IO.raiseError(new Exception("blah")).attempt.flatTap {
      case Left(t) => IO.delay(t.printStackTrace())
      case Right(_) => ???
    }.void
}
```

Cats Effect 2 output:
```
java.lang.Exception: blah
	at Main$.run(Main.scala:7)
	at flatTap @ Main$.run(Main.scala:7)
	at void @ Main$.run(Main.scala:7)
	at run$ @ Main$.run(Main.scala:5)
	at main$ @ Main$.main(Main.scala:5)
```

Cats Effect 3 new output (This PR):
```
java.lang.Exception: blah
	at Main$.run(Main.scala:7)
	at flatTap @ Main$.run(Main.scala:7)
	at void @ Main$.run(Main.scala:7)
	at run$ @ Main$.run(Main.scala:5)
```

cc @Daenyth

**Comment by vasilmkd** [comment]
The idea is the following:

Each time an exception is caught, we push it through the `failed` path of the runloop. It makes sense to augment the exception here.

Funnily enough, this works for everything _except_ the immediate interpreter for `Attempt`, which directly sends caught exceptions to the `succeeded` path by wrapping them in a `Left(...)`. That's why, the two cases where this happens have special cased augmentation and are marked with comments.

**Review by djspiewak — APPROVED** [review]
Awesome!

**Pull request merged**
