### PR TITLE
Mark IOApp#main as final.

### PR DESCRIPTION
**Pull request by kevinmeredith**
Addresses https://github.com/typelevel/cats-effect/issues/604.

### CODE REVIEW

**Comment by kevinmeredith** [comment]
Without looking in depth at the failed builds, my guess is that a flaky test was to blame. Anyway, I'll look in-depth if they fail again.

**Comment by djspiewak** [comment]
`IOAppCompanionPlatform.scala:108`

Apparently we override `main`? For… reasons?

**Comment by kevinmeredith** [comment]
> IOAppCompanionPlatform.scala:108
> Apparently we override main? For… reasons?

Given what you noted, @djspiewak, in https://github.com/typelevel/cats-effect/blob/master/core/jvm/src/main/scala/cats/effect/internals/IOAppCompanionPlatform.scala#L102-L122, does that mean it's incorrect to mark `def main` as `final`?

**Comment by alexandru** [comment]
Ah, you can't make `main` final because indeed we've got `IOApp.WithContext`.

`IOApp.WithContext` is a helper meant to provide a way to override the `ExecutionContext` via a `Resource`. The normal `IOApp` uses a thread-pool for daemonic threads, whereas `WithContext` can use a non-daemonic thread-pool.

So no, you can't make it final.

**Comment by alexandru** [comment]
Also this change should fail the Mima checks too for binary compatibility, because turning a method into a final one does break bin compat.

**Comment by kevinmeredith** [comment]
I'm closing per @alexandru's explanation, https://github.com/typelevel/cats-effect/pull/605#issuecomment-522124710.

**Comment by rossabaker** [comment]
I'm gradually becoming convinced that daemonic main pools are not also demonic. `WithContext` is something I'd like to revisit in CE3.

**Comment by alexandru** [comment]
I think we need to revisit `IOApp` as a whole. I'm bothered that `IOApp` objects are side-effectful.

`main` should have the thread-pool injected, instead of keeping a reference around as a class member.

**Comment by djspiewak** [comment]
> main should have the thread-pool injected, instead of keeping a reference around as a class member.

I mean, does it really matter though? `IOApp` is *the* end of the world, barring sbt shenanigans. What advantage would be gained from injecting the thread pool rather than just effectfully creating it?

**Comment by alexandru** [comment]
`main` would be easier to test, being just an `IO` value. Right now the `IO` value from `main` captures shared state and is not pure. Works for practical purposes, but it's also setting a bad example.

Although if we adopt Monix's design for injecting the `ExecutionContext` in `unsafeRun`, the problem would take care of itself, but not for `Timer` (Monix has `Scheduler` which can also schedule stuff with delays, so `Timer` is also pure).

**Comment by djspiewak** [comment]
> main would be easier to test, being just an IO value. Right now the IO value from main captures shared state and is not pure. Works for practical purposes, but it's also setting a bad example.

I think `main` is pretty much as easy/hard to test regardless. We can't really *do* anything with the `IO` value other than run it, which of course is just as impure as the `ExecutionContext` it closes over.

We're definitely going to adopt Monix's context reader design in CE3. There are just so many advantages and very very few reasons not to. Whether or not we include the timer with that is a different question. I tend to think not, given that just having a single timer per system seems to be optimal in literally every use case.

**Comment by SystemFw** [comment]
> I tend to think not, given that just having a single timer per system seems to be optimal in literally every use case.

injecting `TestContext` for tests through implicits is suboptimal imho

**Pull request closed without merging**
