### PR TITLE
Use a custom jabba index

### PR DESCRIPTION
**Pull request by vasilmkd**
When in doubt, roll your own JDK index.

As a bonus, you get to use the proper names of the JDK versions.

### CODE REVIEW

**Comment by vasilmkd** [comment]
For anyone interested, here's the index I created.

https://github.com/vasilmkd/jdk-index/blob/9a261f33764d7a9f4dd0634495209ebe63836f56/index.json

**Comment by vasilmkd** [comment]
For better integration, we could move the index file to the Cats Effect repository, however there's a slight chicken and egg problem. We need to merge the file in the repository first and then make the build configuration switch in a subsequent PR.

**Comment by vasilmkd** [comment]
I know this is another thing to manage, but I plan to take that responsibility on myself. I've already been doing this for the past year. Unfortunately, the upstream jabba project seems inactive and they haven't been merging PRs or updating the index for months now.

IMO, Cats Effect needs to test on the latest Java versions as soon as they come out, and this is how I intend to do that.

**Comment by armanbilge** [comment]
> Cats Effect needs to test on the latest Java versions as soon as they come out

Pedagogical question: why? 😅

**Comment by vasilmkd** [comment]
It's a foundational library, and I like to test that the runtime does not make some assumptions that future versions of the JDK won't like. I said IMO at the beginning of the sentence. 😄

**Comment by armanbilge** [comment]
> I said IMO at the beginning of the sentence

I know, I reckoned it's a good one so wanted to learn more :)

> the runtime does not make some assumptions that future versions of the JDK won't like

Are there places where it's pushing the boundary of the spec?

**Comment by vasilmkd** [comment]
We definitely don't violate it, but the async node of the `IOFiber` run loop and `cats.effect.unsafe.LocalQueue` do exercise the Java Memory Model quite a bit.

**Comment by armanbilge** [comment]
Presumably, a regression there would be a major regression in Java itself?

**Comment by armanbilge** [comment]
> Cats Effect needs to test on the latest Java versions as soon as they come out

It sounds like to me, we should be testing _before_ they come out, and alerting them to regressions.

**Comment by vasilmkd** [comment]
I'm sure they have a much more strict process of making sure something like that doesn't happen. But there was also an open call to test against JDK 17 [recently](https://contributors.scala-lang.org/t/scala-community-build-on-jdk-17/5153) (we did and it works [fine](https://github.com/typelevel/cats-effect/pull/2135)). It's not just testing against the JMM, but also making sure the Scala versions work properly and that the build passes reliably. It's a sort of an integration test.

I do agree that we should test against early access builds, but I'm not convinced that that's something we need to do all the time. In any case, the official jabba JDK index is too slow to include current or future versions, which IMO is another argument in favor of a custom, lean index, updateable at our own leisure.

**Comment by armanbilge** [comment]
> making sure the Scala versions work properly and that the build passes reliably

Just my opinion, but this sounds like concerns for upstream Scala itself :)

> the official jabba JDK index is too slow to include current or future versions, which IMO is another argument in favor of a custom, lean index, updateable at our own leisure.

This makes sense.

**Comment by vasilmkd** [comment]
Furthermore, the JDK release process has changed since Java 9, with new patch versions dropping regularly every 3 months and each patch release comes with an advice to upgrade, de-facto making it the only supported version of that major JDK version. (i.e. 16.0.2 dropped two weeks ago making 16.0.1 obsolete).

**Comment by vasilmkd** [comment]
> Just my opinion, but this sounds like concerns for upstream Scala itself :)

This is my personal opinion, I love the Scala language, I love the Scala open-source community, and I want everyone to be their best, do the absolute best work they can spare time for, and this includes being a good community citizen. I personally think Cats Effect should lead by example.

That being said, all of what I mentioned in this comment has nothing to do with this PR. In the end we might decide against this change and that's fine. I just thought of an alternative and I proposed it. (I'm also not being defensive, I just maybe failed to convey my initial intentions).

**Comment by armanbilge** [comment]
In that spirit, maybe the JDK index should be a Typelevel repo that can be used by all typelevel projects? Also reduces the bus factor.

**Comment by vasilmkd** [comment]
Or `djspiewak/sbt-github-actions`. I think that would be the easiest integration point.

**Comment by rossabaker** [comment]
One day, the world will embrace the good news that is Nix.  Until then, if it's just a URI, the Typelevel repo sounds smart to me, unless sbt-github-actions has more than a couple people with merge rights.

**Review by djspiewak — APPROVED** [review]

**Pull request merged**
