### PR TITLE
`modifyAndReturn` -> `modify`, `modify` -> `modify_`

### PR DESCRIPTION
**Pull request by SystemFw**
As per [this](https://github.com/typelevel/cats-effect/pull/204#issuecomment-388805220)

### CODE REVIEW

**Comment by johnynek** [comment]
one thing I am *bit* nervous about is that ususally `_` means the exact same method but returning `F[Unit]`. In this case the argument is also different.

I wonder if we can think just a bit more, or refute my claim.

**Comment by SystemFw** [comment]
@johnynek Sure, no rush. 
My main point is `modifyAndReturn` becoming `modify` (which iirc was also your initial suggestion), since it ends up being needed almost always.

I hear your concern, however in this case if we was just the same method with the result discarded, I'd probably not even add it (and use `.void` explicitly). In this case `_` _feels_ right as in "we don't care about the output", but open to other naming suggestions ofc

**Comment by johnynek** [comment]
yeah, I am not crazy about `modifyAndReturn`.

here are some possible synonyms: adjust, transform, mutate... We could use `adjust` to be the kind where you don't get a result, but the problem is that it might be easy to confuse the two.

If we want to keep the single name, I would call it `modify0` or something following the idea that we sometimes just append numbers to refer to highly related, but less frequently used names.

**Comment by SystemFw** [comment]
I think I prefer `modify_` to `modify0` 😿 
It carries slightly more info in my opinion

**Comment by johnynek** [comment]
`modifyValue`?

**Comment by alexandru** [comment]
In Monix I used transform, transformAndGet versus transformAndExtract. Names where inspired by Scala-STM.

modify_ doesn’t sound good. What about modifyAndExtract? It’s a mouthful, but at least you can read it.

**Comment by alexandru** [comment]
So ignore my previous message.

Just wanted to say that modify_ sounds awful 🙂

**Comment by SystemFw** [comment]
I don't see why `modify_` is so awful, it's a convention that cats uses quite often.
The other suggestion I can offer is `modifyAndReturn -> modify`, `modify -> update`

**Comment by SystemFw** [comment]
I actually do like `update` better than `modify_`, do you guys think it's an acceptable compromise?
It's true that the names don't really help you distinguish between the two, but you still have the types that make it quite clear (precedent: `handleErrorWith` vs `recoverErrorWith`).
`modifyAndReturn` would be quite the central operation (especially when you need to run an action that depends on modification like you can see in the fs2 PR), so it would be good if it wasn't that long to spell, and `update` isn't bad at all for the simple use cases

**Comment by johnynek** [comment]
so cats.data.State is quite related and uses `def modify` for `S => S` returning `Unit`: https://github.com/typelevel/cats/blob/master/core/src/main/scala/cats/data/IndexedStateT.scala#L299 

So, I wonder if we should use the same convention here...

maybe we should be finding a new name for the `A => (A, B)` variant since currently `modify` does match State.

**Comment by SystemFw** [comment]
the difference in State is that you can `get`, run an action, and `set`, which doesn't work with `Ref`, so `Ref.modify` is a lot more prominent than any other operation, and deserves the easier/better name.
Or in other words, concurrent state (Ref) and serial state (State) are different enough than a perfect match between the two is not as important to me
I'm afraid the whatever other name we can get for `modify` will be unwieldy (i.e. have `and` in it).
What's the issue with `update` instead of `modify_`?

**Comment by SystemFw** [comment]
and finally for STM , where the `get`, run and `set` _does_ work (so like State, but unlike `Ref`), you are back to
```haskell
modifyTVar :: TVar a -> (a -> a) -> STM ()
```

**Comment by SystemFw** [comment]
Final data point I think, Haskell IORef allows both concurrency-safe and concurrency-unsafe modification, and has:
```haskell
modifyIORef :: IORef a -> (a -> a) -> IO () 
atomicModifyIORef :: IORef a -> (a -> (a, b)) -> IO b
```

So basically every time the modification needs to be atomic the `(a,b)` version unsurprisingly pops up

**Comment by johnynek** [comment]
that's a good point: `a -> a` can be deferred and composed with other updates and possibly applied lazily before a future read.

Since you can't observe this, it seems fine for an implementation to compose a series of modifications into a single call to compareAndSet.

In fact, i guess you can compose two `a -> (a, b)` as well into a `a -> (a, (b, c))` then we could update two open Deferred results to only do a single compareAndSet on the underlying value.

Anyway, not clear that can be an actual performance optimization for us.

**Comment by alexandru** [comment]
@SystemFw this is just bike shedding at this point, so I don't really care that much, but what about `modify -> modifyUnit`, `tryModify -> tryModifyUnit`.

Dictionary definition for "unit":  component, part, section, element, constituent, subdivision, portion, segment, module, item, member, ingredient, factor, feature, piece, fragment; entity, whole, discrete item.

This ties into what you mentioned above, about Haskell using "atomic". But "atomic" is not what I'd like because it has other connotations for us (e.g. thread-safe or non-cancelable).

**Comment by SystemFw** [comment]
I think `modifyUnit` for `modify[B](f: A => (A, B)): F[B]` is super confusing tbh, because people would be wondering why `modifyUnit` doesn't return `F[Unit]`.

**Comment by ChristopherDavenport** [comment]
I really prefer these conventions to `modifyUnit` which I don't think adds semantic value as unit there is not an apparent context of what that means.

**Comment by alexandru** [comment]
Well I preferred the old naming to be honest. I don't mind working with a `modifyAndReturn`.

But that's enough bike-shedding 🙂 Will merge as is.

**Pull request merged**
