### PR TITLE
[naming things] CE3: Rename `yielding` to `cede`

### PR DESCRIPTION
**Pull request by kubukoz**
So long, `yielding`...

### CODE REVIEW

**Comment by djspiewak** [comment]
FWIW, I think `surrender` is a better name in and of itself, but `yield` has such clear precedent and connotation within this space that I think `yielding` might be better overall.

**Comment by alexandru** [comment]
We should name it `yield` instead of `yielding`.

Precedent: [Thread.yield()](https://docs.oracle.com/javase/7/docs/api/java/lang/Thread.html#yield())

**Comment by alexandru** [comment]
> We should name it yield instead of yielding

Replying to myself, `yield` is unfortunately a Scala keyword, so we probably can't use it.

**Comment by tplaskowski** [comment]
Have you considered `cede` as an alternative?  
It' a synonym for `yield`, and it's shorter than `surrender`. Of course, if you still want to change from `yielding`.

**Comment by milessabin** [comment]
Yay! Bikeshedding time!

I quite like `cede`.

Seeing as we're passing the parcel or maybe skipping a turn ... `pass`?

**Comment by djspiewak** [comment]
`cede` is really super-nice, and unlike `yielding`, it is correctly conjugated.

**Comment by rossabaker** [comment]
:+1: to `cede`

**Comment by fsvehla** [comment]
How about `yieldNow`?

**Comment by djspiewak** [comment]
@fsvehla That works as well. It's kind of a padding non-word added onto `yield` to avoid the keyword problem.

**Comment by djspiewak** [comment]
Executive decision! Let's go with `cede` for now. If you feel strongly opposed to this, feel free to flame me on twitter (or here) and make your case. :-) Nothing is set in stone!

**Comment by kubukoz** [comment]
@djspiewak here you go :)

**Pull request merged**
