### PR TITLE
Fix unresolved links in 2.x docs

### PR DESCRIPTION
**Pull request by antonkw**

### CODE REVIEW

**Comment by vasilmkd** [comment]
@antonkw I remembered how to test this.

In your branch:
```
sbt coreJVM/doc docs/mdoc
```

It seems that now the docs are even more confused. Removing the `.md` is not a solution unfortunately. Can you try again?

**Review by vasilmkd — CHANGES_REQUESTED** [review]
Marking as changes needed because there are still warnings in the docs.

**Comment by antonkw** [comment]
Will check with command you've shared.
I saw that original warnings disappeared, plus generated links started to direct me to right pages instead of 404.

**Comment by vasilmkd** [comment]
It's the same set of commands used in the `build.sh` script. :)

**Comment by alexandru** [comment]
Those links should be somehow checked by the build process. They were specified as `.md` because AFAIK Jekyll was able to do that.

**Comment by vasilmkd** [comment]
@antonkw I want to thank you for your effort. I'm going to close this PR now, because I have identified and fixed the issue in #2005. It was a misconfiguration in the documentation build script and no changes to the links themselves were needed.

**Pull request closed without merging**
