### PR TITLE
Thin ci a bit

### PR DESCRIPTION
**Pull request by armanbilge**

### CODE REVIEW

**Comment by armanbilge** [comment]
Cool, I think this is down to 20 checks from 30 on main.

**Comment by vasilmkd** [comment]
Is it better to state the sets of versions explicitly? Currently, the outcome is dependent on how they're ordered in the lists above. I know we control both, I'm just saying changing the former may have unintended consequences later in the file.

**Comment by armanbilge** [comment]
Also is there any hope for this windows ci?

**Comment by vasilmkd** [comment]
Most of the `IOApp` tests are disabled on Windows. I don't think it would be the end of the world if we disabled them all.

**Comment by armanbilge** [comment]
Down to 19!

**Comment by djspiewak** [comment]
We can probably cut this down even further by removing the JavaScript tests on Windows and Mac.

**Edit:** Nvm they already are derp

**Review by djspiewak — APPROVED** [review]

**Pull request merged**
