### PR TITLE
Add Scala3 / JDK17 job to CI

### PR DESCRIPTION
**Pull request by armanbilge**
Forgot my promise to do this in https://github.com/typelevel/cats-effect/pull/2857#issuecomment-1065514957 :)

Expecting the first commit to fail with the MiMa issues. Will follow-up with exclusions.

### CODE REVIEW

**Comment by armanbilge** [comment]
Huh. I can no longer reproduce the MiMa issues locally 🤔

**Comment by armanbilge** [comment]
Oh lol I guess the filters were already in place 😅 I must have added them in anger when trying to get MiMa to pass on my local, woops 🙃 

https://github.com/typelevel/cats-effect/blob/0177c4aff70756b1f715da17d7e0826903ec9640/build.sbt#L526-L535

**Review by djspiewak — COMMENTED** [review]
Doesn't this actually *remove* the Scala 3 + JDK 17 job?

**Comment by armanbilge** [comment]
Um, no?
https://github.com/typelevel/cats-effect/runs/6121004966?check_suite_focus=true

**Comment by djspiewak** [comment]
Oh, it's the exclusion matrix. Sorry, not enough coffee

**Review by djspiewak — APPROVED** [review]

**Pull request merged**
