### PR TITLE
Correct `IO#racePair` docs

### PR DESCRIPTION
**Pull request by TimWSpence**

### CODE REVIEW

**Review by armanbilge — DISMISSED** [review]
Thanks!

**Comment by armanbilge** [comment]
Oh, actually can this be re-targeted at 3.3.x?

**Comment by TimWSpence** [comment]
> Oh, actually can this be re-targeted at 3.3.x?

I tried and failed horribly 😂 What is the preferred approach to this? Change the base in GH and then rebase my branch onto 3.3.x?

**Comment by armanbilge** [comment]
Yeah, unfortunately can't be done just from GH :)

**Comment by TimWSpence** [comment]
> Yeah, unfortunately can't be done just from GH :)

Yeah I suspected not! Done now (I think 😂 )

**Comment by djspiewak** [comment]
This is great. It does need a run of `sbt prePR` though :-)

**Review by djspiewak — DISMISSED** [review]
This is great. It does need a run of sbt prePR though :-)

**Comment by djspiewak** [comment]
So correction: docs stuff should ideally be targeted at `series/3.x`. Sorry to keep bouncing it around a bit :-)

**Comment by armanbilge** [comment]
Wait, why is that? Are we publishing the docs from 3.x?

Edit: If we are, that doesn't make sense because it means are publishing docs for new APIs e.g. `allocatedCase` that have not yet been published. Furthermore, this fix should benefit users who read their scaladocs in their IDE. In both cases, I would think we want it merged into 3.3.x.

**Review by armanbilge — APPROVED** [review]

**Pull request merged**
