### PR TITLE
Add ExitCase.toOutcome

### PR DESCRIPTION
**Pull request by joroKr21**
For completeness. I'm not sure how useful it would be in practice.

### CODE REVIEW

**Comment by djspiewak** [comment]
This is definitely worth having in lieu of #1110

**Comment by joroKr21** [comment]
I'm not sure why the build failed

**Comment by djspiewak** [comment]
It's apparently hanging the windows build? Weird…

**Comment by vasilmkd** [comment]
Java 15 on Windows fails very often. It has nothing to do with any of the code, it's some GitHub Actions issue (either with the runners or with some setup actions, not sure).

**Comment by djspiewak** [comment]
So strange. Probably worth pulling it out of the matrix for now, but it's really odd behavior.

**Review by mpilquist — APPROVED** [review]

**Pull request merged**
