### PR TITLE
Live fiber snapshot on the JVM

### PR DESCRIPTION
**Pull request by vasilmkd**
We'll tweak the text and add trace info in follow ups.

### CODE REVIEW

**Review by armanbilge — APPROVED** [review]
These dumps are gonna be pretty massive I guess 😅

**Comment by vasilmkd** [comment]
Yeah... One day, we'll be paid to build tooling around it. ;)

**Comment by armanbilge** [comment]
😆 just wait till these become 2-dimensional w/ Daniel's full-tracing plan!

**Comment by vasilmkd** [comment]
We'll make them navigable along the dimensions. 😆

**Comment by armanbilge** [comment]
VR tracing 😎

**Comment by vasilmkd** [comment]
You heard it here first 😎

**Pull request merged**
