### PR TITLE
Cancel 2.5.2

### LINKED ISSUE #2195: Cats Effect 2.5.2 is slightly botched
We have not included the `SyncIO.defer` and `IO.defer` additions.

The `v2.5.2` tag is made at this [commit](https://github.com/typelevel/cats-effect/commit/cfb40e69810f586b227fd9db17e99e9839ef421f), but the aforementioned changes landed in a PR _after_ it.

@djspiewak You are my only hope.

### PR DESCRIPTION
**Pull request by djspiewak**

### CODE REVIEW

**Comment by vasilmkd** [comment]
I think you missed renaming the `v2_5_2` directory to `v2_5_3`. It should show up as an error in the CI.

**Comment by vasilmkd** [comment]
Shoot, can you please also remove the `scalafix/.bsp` directory and add it to a `.gitignore`? I didn't notice it was added last time I was making changes. I'm sorry.

**Comment by djspiewak** [comment]
> I think you missed renaming the v2_5_2 directory to v2_5_3. It should show up as an error in the CI.

Oddly it didn't show up as an error, but I'll fix it anyway.

**Comment by vasilmkd** [comment]
By examining the logs, the tests just didn't run:
```
[info] welcome to sbt 1.5.5 (AdoptOpenJDK Java 11.0.11)
10
[info] loading settings for project scalafix-build from plugins.sbt ...
11
[info] loading project definition from /home/runner/work/cats-effect/cats-effect/scalafix/project
12
[info] loading settings for project scalafix from build.sbt ...
13
[info] set current project to scalafix (in build file:/home/runner/work/cats-effect/cats-effect/scalafix/)
14
[info] compiling 2 Scala sources to /home/runner/work/cats-effect/cats-effect/scalafix/v2_4_0/input/target/scala-2.13/classes ...
15
[info] compiling 2 Scala sources to /home/runner/work/cats-effect/cats-effect/scalafix/v2_4_0/output/target/scala-2.13/classes ...
16
[info] done compiling
17
[info] done compiling
18
[info] compiling 2 Scala sources to /home/runner/work/cats-effect/cats-effect/scalafix/rules/target/scala-2.13/classes ...
19
[info] done compiling
20
[info] compiling 1 Scala source to /home/runner/work/cats-effect/cats-effect/scalafix/v2_4_0/tests/target/scala-2.13/test-classes ...
21
[info] done compiling
22
[info] CatsEffectTests:
23
[info] - fix/SyncRewrites.scala
24
[info] - fix/ResourceRewrites.scala
25
[info] Run completed in 1 second, 475 milliseconds.
26
[info] Total number of tests run: 2
27
[info] Suites: completed 1, aborted 0
28
[info] Tests: succeeded 2, failed 0, canceled 0, ignored 0, pending 0
29
[info] All tests passed.
30
[success] Total time: 16 s, completed Aug 4, 2021, 7:14:30 PM
```

**Comment by rossabaker** [comment]
Uh, is 2.5.3 supposed to be out already?  Scala Steward has already found it.

**Comment by vasilmkd** [comment]
`2.5.3` is out already. We're fiddling with the scalafix tests that were supposed to work with `2.5.2` but there was a mistake when publishing that version.

The only changes are the additions of `IO.defer` and deprecation of `IO.suspend`. Same for `SyncIO`.

**Review by vasilmkd — APPROVED** [review]

**Comment by vasilmkd** [comment]
Merge at will.

**Pull request merged**
