### PR TITLE
Fix mutex cancelled acquire

### PR DESCRIPTION
**Pull request by durban**
Fix Async mutex acquire to be cancellation-safe.

### CODE REVIEW

**Comment by armanbilge** [comment]
Unfortunately this doesn't seem to have fixed the Skunk issue 😕  tried it in https://github.com/armanbilge/skunk/commit/7a2ab6a0b8971a633cc635dae79562f777e4a36c.

**Comment by armanbilge** [comment]
The test you added is good but unfortunately it's affected by https://github.com/typelevel/cats-effect/issues/3503 😕

**Comment by armanbilge** [comment]
Is this cancelation safe? Can the `async` which created this `waiter` be canceled before it is invoked?

https://github.com/typelevel/cats-effect/blob/c760a55de5bbeaf2e19b774b0a144a20bec42105/std/shared/src/main/scala/cats/effect/std/Mutex.scala#L127-L129

**Comment by durban** [comment]
Yeah, I think that's the same problem as the one was with `Queue`. Probably could be fixed the same way...

**Comment by armanbilge** [comment]
Oh right. How was that one fixed? 😆

**Review by djspiewak — APPROVED** [review]

**Pull request merged**
