### PR TITLE
introduced Ref.modifyF and Ref.tryModifyF

### PR DESCRIPTION
**Pull request by pchlupacek**
This is slight modification to Ref, that introduces optimalised versions of modify and tryModify when `B` is lifted to `F`. 

This gives 5-10% performance increase over Ref.modify(...).flatten and Ref.tryModify(...).flatMap(...) constructs. 

Even-though the modify and tryModify could be implemented in terms of modifyF/tryModifyF with no overhead introduced(thanks to implementation of Sync#delay), certain `F` may override this for optimisations, like for example IO does. I decided to leave the former implementations as-is.

### CODE REVIEW

**Comment by pchlupacek** [comment]
@SystemFw I will add them in this PR

**Comment by pchlupacek** [comment]
btw why MIMA is complaining?

**Comment by alexandru** [comment]
> btw why MIMA is complaining?

Because you're breaking binary compatibility ☹️

Fortunately we used abstract classes, so you can workaround it by adding a default implementation.

**Comment by pchlupacek** [comment]
aha, I am completely lost in what is/not breaking compatibility. Thanks @alexandru

**Comment by SystemFw** [comment]
so I guess we can indeed have `modify(...).flatten` as the default, and override it in concrete implementations?

**Comment by pchlupacek** [comment]
@SystemFw good catch. @alexandru I am not familliar that deep in IO implementation whats your bet here. Does the IO.delay has a significant win over IO.suspend(IO.now()) ?

**Comment by alexandru** [comment]
`IO.delay` is a little better than `IO.suspend(IO.now())`. The underlying logic avoids the boxing. And both are little better than `IO.delay(IO.now()).flatten`.

**Comment by pchlupacek** [comment]
@SystemFw to override complete implementations we would need users to create their own refs, unless I miss something... 
@alexandru  thanks for clarification

**Comment by pchlupacek** [comment]
I perhaps may extract spin and introduce `F` as type parametere and fill it with Id/F when necessary ?

**Comment by alexandru** [comment]
`Ref` is defined as an `abstract class` but you can't add abstract methods to it without breaking binary compatibility. Hence the new methods need a default implementation that you can then override.

On this PR, if we do this for performance reasons, we probably need a simple benchmark.

**Comment by SystemFw** [comment]
@pchlupacek I mean that `Ref` is an abstract class, but you do need to have a default implementation to avoid breaking bincompat, and `modify(...).flatten)` is the only one you can have since it only relies on other `Ref` ops. Then, in `SyncRef`, you add the actual implementation you have now

**Comment by pchlupacek** [comment]
@alexandru ypu mean benchmark in `benchmarks`? Is there somewhere described how previous/next works?

**Comment by SystemFw** [comment]
👍 on a simple benchmark

**Comment by pchlupacek** [comment]
@SystemFw aha gotcha :-)

**Comment by alexandru** [comment]
@pchlupacek not necessarily. I saw you said you saw a 5-10% improvement. Pasting the benchmark code in a Gist and a copy/paste of the raw results would be enough.

**Comment by pchlupacek** [comment]
I am just asking b/c I cannot get the benchmarks to compile on master, so I am not sure what I am doing wrong there ....

**Comment by alexandru** [comment]
And if we have those improvements, I'm 👍  on the changes.

It also makes the API less awkward, because in `CircuitBreaker` you end up with a annoying dangling `.flatten`.

**Comment by alexandru** [comment]
> I am just asking b/c I cannot get the benchmarks to compile on master, so I am not sure what I am doing wrong there ....

The `benchmarks` aren't actively maintained because they aren't integrated in the build process and nobody checks them. They might need some cleaning up.

It's also meant for guarding against regressions, so when you have the same code between the previous version and the current master. Not really the case here.

**Comment by pchlupacek** [comment]
There is the benchmark: 

```scala


  @Benchmark
  def old: Int = {
    def runSteps(ref: Ref[IO, Long], steps: Int): IO[Long] = {
      def go(rem: Int): IO[Long] =
        if (rem == 0) IO.pure(0l)
        else ref.modify[IO[Long]] { l => (l, go(rem-1))}.flatten

      go(steps)
    }

    Ref.of[IO, Long](0l).flatMap { ref =>
      runSteps(ref, size)
    }.unsafeRunSync().toInt
  }


  @Benchmark
  def updated: Int = {
    def runSteps(ref: Ref[IO, Long], steps: Int): IO[Long] = {
      def go(rem: Int): IO[Long] =
        if (rem == 0) IO.pure(0l)
        else ref.modifyF[Long] { l => (l, go(rem-1))}

      go(steps)
    }

    Ref.of[IO, Long](0l).flatMap { ref =>
      runSteps(ref, size)
    }.unsafeRunSync().toInt
  }

```

```

[info] RefBenchmark.old        1000  thrpt   20  44410.018 ± 2881.708  ops/s
[info] RefBenchmark.updated    1000  thrpt   20  47613.382 ±  567.670  ops/s

```

**Comment by pchlupacek** [comment]
as regards to MIMA -> I need Monad//FlatMap in order to implement defaults. If I add them to abstract class I think MIMA will scream wouldn't it?

**Comment by pchlupacek** [comment]
@alexandru , @SystemFw not really sure what to do with Mima here any suggestions? 
Thanks.

**Comment by SystemFw** [comment]
I think the only way to do is to add `FlatMap[F]` to the signature of `modifyF`in the abstract class. Not sure if that will work when overriding it. It might, but you will ignore the parameter.

**Comment by pchlupacek** [comment]
@SystemFw ok that seems doable

**Comment by alexandru** [comment]
Any updates on this?

**Comment by pchlupacek** [comment]
I would like to get this done, not sure though how to avoid this bincompat issue? You think that @SystemFw suggestion will just work?

**Comment by alexandru** [comment]
@pchlupacek unfortunately when designing these abstract classes, we should have also added the `F[_] : Sync` restriction on them — because indeed, we cannot add other abstract methods on them.

Specifying an `F[_] : FlatMap` restriction on the operation is indeed the only way forward if we want these two operations in Cats-Effect 1.x.

I don't have much experience with `Ref`, but if you think these are worth it, then we can work with that restriction.

**Comment by djspiewak** [comment]
@pchlupacek We're making some binary incompatible changes in the soon-to-be-forthcoming 2.0, so if that's the blocker here, there's an opportunity to get things through.

**Comment by pchlupacek** [comment]
@djspiewak how much time I do have for that?

**Comment by djspiewak** [comment]
@pchlupacek Until maybe a week or two after 2.13 at the latest, I would assume, preferably closer to around when 2.13 drops. It depends a bit on cats. We're going to release 2.0.0-M1 first, and I'd be okay breaking compatibility up to 2.0.0-RC1.

**Comment by alexandru** [comment]
We should not break BC for Scala 2.12.

If we break compatibility, we need to break it in a more ambitious way here. The restriction on these traits should be enforced via a trait member, otherwise it keeps us from adding derived utilities such as these and we'll keep breaking BC with each new idea we have.

However I'd rather leave that for CE 3.

**Comment by alexandru** [comment]
Also Cats-Effect 2.0 should be in feature freeze right now. So I hope you guys are thinking of 2.1.

**Comment by kubukoz** [comment]
We're post 2.1 now, probably a good time to revive this :)

I'm 👍 for adding `FlatMap` constraints to the new methods. Breaking BC isn't worth it.

**Pull request closed without merging**
