### PR TITLE
Prepare the v0.5 release

### PR DESCRIPTION
**Pull request by rossabaker**

### CODE REVIEW

**Comment by rossabaker** [comment]
A lot of projects are blocked on this, so we should move quickly.  But it'd be delightful if #79 made the bus.

**Comment by djspiewak** [comment]
Good job increasing code coverage on a readme change!  Wish I could pull off that trick… :-P

I'm merging both your PRs now.  5.0 should be out shortly.

**Comment by alexandru** [comment]
> I'm merging both your PRs now. 5.0 should be out shortly.

I feel like I've read a message from the future :-P

**Comment by djspiewak** [comment]
> I feel like I've read a message from the future :-P

Jetlag is rough. :-)  0.5

**Pull request merged**
