### PR TITLE
Upgrade to cats-2.2.0-RC1

### PR DESCRIPTION
**Pull request by rossabaker**
Since our main dependency is in RC stage, it would be nice if we released on it.

### CODE REVIEW

**Review by LukaJCB — APPROVED** [review]
Good call!

**Comment by rossabaker** [comment]
Is there a scala.js doctor in the house?

```
[error] org.scalajs.ir.IRVersionNotSupportedException: Failed to deserialize a file compiled with Scala.js 1.1 (supported up to: 1.0): /home/travis/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scala-js/scalajs-library_2.12/1.1.1/scalajs-library_2.12-1.1.1.jar:/scala/Predef$DummyImplicit$.sjsir
[error] You may need to upgrade the Scala.js sbt plugin to version 1.1 or later.
```

**Comment by djspiewak** [comment]
`sbt clean`?

**Comment by larsrh** [comment]
Pretty sure this one requires #1010 to land.

**Comment by larsrh** [comment]
@rossabaker Could you rebase and push again? This should work now

**Comment by djspiewak** [comment]
I believe there is also now an RC2 :-)

**Comment by larsrh** [comment]
Took the liberty to rebase.

**Review by larsrh — APPROVED** [review]

**Pull request merged**
