### PR TITLE
Fix infinitely waiting cancellation of a bracket which failed to acquire. Fixes #487

### LINKED ISSUE #487: IOApp hangs when Resource contains exception
It looks like `IOApp` didn't handle all error cases.

In the following example, I expect that the application will finish with the error code and print stack trace in the console:

```scala
import cats.effect.{ExitCode, IO, IOApp, Resource}

object ResourceIoAppTest extends IOApp {
  override def run(args: List[String]): IO[ExitCode] = {
    val r = Resource.liftF(IO.delay(throw new RuntimeException("Test")))
    r.use { _ =>
      IO.delay(ExitCode.Success)
    }
  }
}
```

But actual behavior differs: application prints stack trace and hangs. It could be killed only with `kill -9`.

When I run this app with the `sbt run` I see this: 
```
java.lang.RuntimeException: Test
        at cats.effect.internals.ResourceIoAppTest$.$anonfun$run$1(Foo.scala:23)
        at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:87)
        at cats.effect.internals.IORunLoop$.start(IORunLoop.scala:34)
        at cats.effect.internals.IOBracket$.$anonfun$apply$1(IOBracket.scala:44)
        at cats.effect.internals.IOBracket$.$anonfun$apply$1$adapted(IOBracket.scala:34)
        at cats.effect.internals.IORunLoop$RestartCallback.start(IORunLoop.scala:337)
        at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:119)
        at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:351)
        at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:372)
        at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:312)
        at cats.effect.internals.IOShift$Tick.run(IOShift.scala:36)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

Exception: sbt.TrapExitSecurityException thrown from the UncaughtExceptionHandler in thread "run-main-0"
```

I tried to investigate this issue and I found, that in `IOAppPlatform.mainFiber` even after `redeem` call the `io` could fail. I changed `io.start(contextShift.value).flatMap` to `io.start(contextShift.value).bracket`. It helps a little: application could now be killed with the simple `kill` command. But the app still hangs and don't finish properly.

### PR DESCRIPTION
**Pull request by RafalSumislawski**
Fixes #487

### CODE REVIEW

**Comment by kubukoz** [comment]
@alexandru can you take a look?

**Comment by rossabaker** [comment]
Apologies for taking so long to look.  This looks reasonable to me.  Would it be possible to add a test here to confirm the fix?

**Comment by RafalSumislawski** [comment]
@rossabaker I've added a test as you requested.

**Comment by kubukoz** [comment]
@RafalSumislawski that seems to have broken the build, can you take another look?

**Comment by RafalSumislawski** [comment]
@kubukoz It should be better now. I had to convince the compiler that the dead code isn't a dead code.

**Pull request merged**
