### PR TITLE
Uncancelable_

### PR DESCRIPTION
**Pull request by TimWSpence**
I thought this pattern was common enough to deserve a dedicated method?

### CODE REVIEW

**Comment by RaasAhsan** [comment]
btw `MonadCancel` syntax includes an `uncancelable` method which behaves like this, should that one be renamed as well?

**Comment by TimWSpence** [comment]
> btw `MonadCancel` syntax includes an `uncancelable` method which behaves like this, should that one be renamed as well?

Oh yep, good call! 👍

**Comment by TimWSpence** [comment]
@RaasAhsan oh actually, I see what you mean. My gut is that `fa.uncancelable` looks better than `fa.uncancelable_` but I'm happy to be persuaded otherwise!

**Comment by RaasAhsan** [comment]
@TimWSpence yeah I'm not really sure here either, but thought it was worth bringing up :)

**Comment by TimWSpence** [comment]
@RaasAhsan we'll wait for someone else to weigh in then 😂 I realized I should have defined it directly on `IO` as well though so I've done that now

**Comment by djspiewak** [comment]
IMO I prefer `fa.uncancelable` to `uncancelable_(fa)`. :-) I think whenever you don't want to use the `syntax`, `uncancelable(_ => fa)` isn't really that onerous.

**Pull request closed without merging**
