### PR TITLE
inlining usages of require in Queue and PQueue

### LINKED ISSUE #1395: Inline require usage within Queue and PQueue
Follow up to https://github.com/typelevel/cats-effect/pull/1361#discussion_r514485777

### PR DESCRIPTION
**Pull request by jyoo980**
Should resolve  #1395

### CODE REVIEW

**Comment by jyoo980** [comment]
Forgot to `scalafmt` lol, will push update.

**Comment by jyoo980** [comment]
Not sure what exactly happened here: https://github.com/typelevel/cats-effect/pull/1543/checks?check_run_id=1611875751#step:12:66

Looks like it might be a JVM issue?

**Comment by djspiewak** [comment]
I think I fixed the issue you uncovered in CI in #1547. It appears to be a very rare bug. I've restarted this build in the interim, but if you keep seeing it, we should probably merge that PR into this one.

**Comment by jyoo980** [comment]
Sounds good, that's an interesting bug

**Pull request merged**
