### PR TITLE
Fix #375, fix #384: force fiber.cancel to wait on completion of brackets, fix laws, fix idempotency of release

### LINKED ISSUE #375: ConcurrentLaws.acquireIsNotCancelable unreasonable assumption about Fiber.cancel
As seen in https://github.com/scalaz/scalaz-zio/pull/267

We have this law:

```scala
  def acquireIsNotCancelable[A](a1: A, a2: A) = {
    val lh =
      for {
        mVar  <- MVar[F].of(a1)
        latch <- Deferred.uncancelable[F, Unit]
        task   = F.bracket(latch.complete(()) *> mVar.put(a2))(_ => F.never[A])(_ => F.unit)
        fiber <- F.start(task)
        _     <- latch.get
        _     <- fiber.cancel
        _     <- contextShift.shift
        _     <- mVar.take
        out   <- mVar.take
      } yield out

    lh <-> F.pure(a2)
  }
```

This law introduces the assumption that `fiber.cancel` doesn't block. In `cats.effect.IO`'s implementation there aren't at that point any finalizers registered so `cats.effect.IO` doesn't block on anything. But ZIO blocks for the completion of that fiber.

Which means that we need a fix that forks the `cancel` operation. E.g. we could use `F.start(fiber.cancel)` instead. Maybe even with an extra `contextShift.shift` just to be sure that it is indeed concurrent.

---

Published hash version with the fix for testing purposes:

```
1.0.0-1182d8c
```

### LINKED ISSUE #384: Release can be called more than once
Because of recent discussions, I have been tinkering around with `bracket` and cancellation. I think I've found some unfavorable behavior that can be illustrated by the following program:

```scala
object TestApp extends IOApp {

  import cats.implicits._
  import scala.concurrent.duration._

  def printLine(message: String): IO[Unit] =
    IO.delay(println(message))

  def blocking: IO[Unit] =
    IO.delay(Thread.sleep(3000))

  override def run(args: List[String]): IO[ExitCode] = for {
    _     <- printLine("start")
    io     = printLine("acquire").bracket(_ => blocking *> printLine("use"))(_ => printLine("release"))
    fiber <- io.start
    _     <- fiber.cancel
    _     <- IO.sleep(5.seconds)
  } yield ExitCode.Success

}
```

If you run the program, you should see the following output:
```
start
acquire
release
use
release
```

When the fiber is cancelled, the `IOConnection` is cancelled so its finalizers are executed (immediately?). However, if `use` does not encounter an cancellation boundary after the fiber is cancelled, [it will go on to run `release` again](https://github.com/typelevel/cats-effect/blob/master/core/shared/src/main/scala/cats/effect/internals/IOBracket.scala#L68). I can verify that the behavior is the same for `guarantee`.

I imagine one way to fix the double release is to insert a cancellation boundary before release, but I think there's the other problem of having the ability to reuse a resource that has already been released.

I haven't seen any discussion or documentation about this, so is this behavior something users of `IO` need to  keep in mind when using `bracket`, or is there an issue here?

### PR DESCRIPTION
**Pull request by alexandru**
Fixes #375.

- Ensures `Fiber.cancel` waits on the completion of any started `bracket`, even when finalizers haven't been installed yet
- Makes synchronous flatMap loops auto-cancelable, but only after a fork (e.g. after a `shift`)
- Fixes laws by doing `F.start(fiber.cancel)` where needed

Fixes #384:

- Somehow missed the idempotency guard in bracket's `release`, which means release can be called twice

### CODE REVIEW

**Comment by pchlupacek** [comment]
@alexandr cool. This mean now we can be always sure, when IO.cancel ends, there is no residue evaluation of IO, except when there is asynchronous code, in which case that will not wait on async `cb` to complete, but rather will render `cb` to be no-op when invoked. Do I get it right?

**Comment by alexandru** [comment]
I've also made made synchronous flatMap loops to be auto-cancelable after a fork (so anything after a `shift`, otherwise there's no "connection" created, so no cancellation is possible) ... this ensures that even "fibers" described with no cancel boundaries will terminate on cancellation.

Now you can bask yourself in the awesomeness of fibers for marketing purposes, even if they aren't real.

@pchlupacek 

> This mean now we can be always sure, when IO.cancel ends, there is no residue evaluation of IO, except when there is asynchronous code, in which case that will not wait on async cb to complete, but rather will render cb to be no-op when invoked. Do I get it right?

In the case of `IO` values created with `bracket` or `cancelable` being started, we ensure that `cancel` blocks for their completion. I also made the run-loop detect cancellation by itself after a fork (so after `start` too), no extra `cancelBoundary` calls needed, which means that all synchronous loops will eventually stop.

So I would say yes to your question, but I'm not going to say it, because I want you to look at the source and play with the implementation, as to not have any misunderstandings about how cancellation works going forward.

**Comment by pchlupacek** [comment]
@alexandru thanks. Will have time something like next week unfortunately, will be away from work by then. Hope thats ok with you.

**Comment by alexandru** [comment]
@pchlupacek no worries. Whenever you have the time.

What's important for me right now is to distribute the knowledge of the internals, I've seen you're capable of dealing with lower level atomic stuff, so I'd appreciate if you took a look at how cancellation works, a fresh pair of eyes can always help.

**Comment by pchlupacek** [comment]
@alexandru sorry that i didn't spare time. Was really under load this week and only time I had I have devoted to fs2-final.

**Pull request merged**
