### PR TITLE
Rewrite intro with four key concepts

### PR DESCRIPTION
**Pull request by valencik**
_This PR targets the `docs` branch_

This PR rewrites the homepage introduction to be shorter and focus on four important concepts.
Namely speed, reliability, the ecosystem, and our community :slightly_smiling_face:.

Preview:
Screenshot from 2022-11-07 06-59-09

Special thanks to @jducoeur, @SethTisue, and @djspiewak for considerable feedback on these changes. Trying to be descriptive and clear in few words is tricky.

Also thank you to all that filled out the informal survey to help identify the four important concepts and how we should be presenting ourselves.

### CODE REVIEW

**Review by jducoeur — APPROVED** [review]

**Review by zmccoy — APPROVED** [review]
Looks great!

**Review by SystemFw — APPROVED** [review]
The wording looks great :)
It's not a part of this PR but I actually worry about the code snippet a bit. It looks "familiar" due to `for`, so that's an advantage, but it also promotes code that actually isn't resource safe/automatically cancels, so it conflicts with point 2 unless we make structured concurrency the default

**Comment by valencik** [comment]
> I actually worry about the code snippet a bit. It looks "familiar" due to `for`, so that's an advantage, but it also promotes code that actually isn't resource safe/automatically cancels, so it conflicts with point 2 unless we make structured concurrency the default

I agree. Tackling the code snippet is next on my plate :)
I'll be sure to ping you for feedback 😁

**Review by armanbilge — APPROVED** [review]
So glad these are the four :)

**Review by djspiewak — APPROVED** [review]
This is great! I do think we should have an unobtrusive image of some sort for each one, but that can be a next step. Also eliminating or rewriting hte code snippet would be good.

**Pull request merged**
