### PR TITLE
Fix CompletableFuture cancelation

### LINKED ISSUE #2903: `Async.fromCompletableFuture` should block if cancelation fails
`Async.fromCompletableFuture` has a [cancel operation](https://github.com/typelevel/cats-effect/blob/a045918379d69c699e8d7b47e6d81dc112aa1eb1/kernel/jvm/src/main/scala/cats/effect/kernel/AsyncPlatform.scala#L45) that completes after calling `cancel` on the underlying `CompletableFuture`, but if the cancelation fails then `CompletableFuture.cancel` will immediately return `false` - fiber cancelation in this case should block until the future completes.

### PR DESCRIPTION
**Pull request by bplommer**
I think this fixes #2903 but I haven't yet written a regression test.

### CODE REVIEW

**Comment by bplommer** [comment]
cc @Daenyth

**Comment by vasilmkd** [comment]
LGTM, but a test would be really good for this.

**Comment by armanbilge** [comment]
We discussed how to write a test on Discord.
https://discord.com/channels/632277896739946517/632278585700384799/956566207211905115

The tl;dr is create an uncancelable "never" `CompletableFuture` that will not complete, and always returns `false` when attempts to be canceled. The correct implementation should get backpressured on cancellation, whereas the broken one should terminate.

**Comment by bplommer** [comment]
There was some discussion on Discord about how to test this - I can't promise to do that in the next couple of days, so feel free to fork this PR with a test.

Edit: what @armanbilge said

**Comment by vasilmkd** [comment]
@armanbilge Can you please handle this? Thanks.

**Comment by armanbilge** [comment]
Yup I'm working on https://github.com/typelevel/cats-effect/issues/2902, I can do this next.

**Comment by vasilmkd** [comment]
Closing in favor of #2907.

**Pull request closed without merging**
